force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Comment__c.field-meta.xml
<CustomField>
    <fullName>OA_Comment__c</fullName>
    <label>Comment</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>OA_Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Forecast</relationshipLabel>
    <relationshipName>OA_Revenue_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Percentage_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>OA_Percentage_Invoiced__c</fullName>
    <label>Percentage Invoiced</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Risk_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>OA_Risk_Adjusted__c</fullName>
    <formula>OA_Sales_Revenue__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Risk Adjusted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Sales_Revenue__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Forecasted monthly revenue</description>
    <label>Sales Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Status__c.field-meta.xml
<CustomField>
    <fullName>OA_Status__c</fullName>
    <description>Status of Delivery and Invoicing Milestones</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Delivery In Progress</fullName>
            </value>
            <value>
                <fullName>Delivery Completed</fullName>
            </value>
            <value>
                <fullName>Invoice Approval Pending</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected</fullName>
            </value>
            <value>
                <fullName>Invoice Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Total_Sales_Revenue_Incl_CRs__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Sales_Revenue_Incl_CRs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Sales Revenue including the changes via various CRs</inlineHelpText>
    <label>Total Sales Revenue (Incl CRs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>OA_Unique_Identifier__c</fullName>
    <description>This field is updated by workflow. Unique Identifier for milestones. Concatenation of Opportunity Id, RecordTypeId, Month and Year.</description>
    <externalId>true</externalId>
    <label>Unique Identifier(Not for layout)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery Milestone</label>
</RecordType>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice Milestone</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/OA_Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>OA_Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Change Request</relationshipLabel>
    <relationshipName>ChangeRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_DisplayMilestoneController.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_DisplayMilestoneController
Class Purpose: Controller for Display Milestones Page
Versions: 1.1
******************************************************************************************************/
public without sharing class OA_DisplayMilestoneController { 
    public boolean haveInvoiceMilestone{get;set;}
    public boolean haveDeliveryMilestone{get;set;}
    public List<MilestoneWrapper> deliveryMilestones{get;set;}
    public List<MilestoneWrapper> invoiceMilestones{get;set;}
    public Integer numberOfCR{get;set;}
    
    public OA_DisplayMilestoneController(ApexPages.StandardController controller){
        if(controller == null || controller.getId() == null || controller.getId() == '') return;        
        Id oppId = controller.getId();
        haveInvoiceMilestone = false;
        haveDeliveryMilestone = false;
        numberOfCR = 2;
        setMilestones(oppId);        
    }
    
    private void setMilestones(Id oppId){
        Map<String,MilestoneWrapper> deliveryMilestonesMap = new  Map<String,MilestoneWrapper>();
        Map<Integer, String> monthMap = OA_Utility.getMonthMap();
        deliveryMilestones = new List<MilestoneWrapper>();
        invoiceMilestones = new List<MilestoneWrapper>();
        Map<String, List<OA_Revenue_Forecast__c>> changeRequestMap = new Map<String, List<OA_Revenue_Forecast__c>>();
        for(OA_Revenue_Forecast__c crMilestone : [SELECT id, Name, OA_Opportunity__r.StageName, OA_Opportunity__c, OA_Opportunity__r.OA_Parent_Project__c, RecordTypeId, OA_Month__c, OA_Year__c, OA_Sales_Revenue__c FROM  OA_Revenue_Forecast__c WHERE OA_Opportunity__r.OA_Parent_Project__c =: oppId]){
            String key = String.valueOf(oppId)+
                         String.valueOf(crMilestone.RecordTypeId)+
                    	 crMilestone.OA_Month__c+
                         crMilestone.OA_Year__c;
            if(!changeRequestMap.containsKey(key)) changeRequestMap.put(key, new List<OA_Revenue_Forecast__c>());
            changeRequestMap.get(key).add(crMilestone);   
            
        }
        System.debug('changeRequestMap:'+changeRequestMap);
        for(OA_Revenue_Forecast__c eachMilestone : [SELECT Id, OA_Total_Sales_Revenue_Incl_CRs__c, OA_Unique_Identifier__c, CurrencyIsoCode, OA_Comment__c,OA_Invoice_Amount__c, OA_Month__c,OA_Year__c , OA_Percentage_Invoiced__c, OA_Risk_Adjusted__c,OA_Sales_Revenue__c,OA_Status__c, RecordType.DeveloperName, RecordType.Name FROM OA_Revenue_Forecast__c WHERE OA_Opportunity__c=: oppId Order by OA_Year__c, OA_Month__c]){
            if(eachMilestone.RecordType.Name == null || eachMilestone.OA_Month__c == null || eachMilestone.OA_Year__c == null) continue;
            MilestoneWrapper milestoneWrapper = new MilestoneWrapper();
            milestoneWrapper.sfId = eachMilestone.Id;
            milestoneWrapper.comment = eachMilestone.OA_Comment__c;
            milestoneWrapper.status = eachMilestone.OA_Status__c;
            milestoneWrapper.currencyType = eachMilestone.CurrencyIsoCode;
            milestoneWrapper.displayMonthYear = monthMap.get(Integer.valueOf(eachMilestone.OA_Month__c))+'\''+String.valueOf(eachMilestone.OA_Year__c).substringAfter('20');
            
            if(eachMilestone.RecordType.DeveloperName.equalsIgnoreCase(OA_Constant.DELIVERY)){
                milestoneWrapper.salesRevenue =  eachMilestone.OA_Sales_Revenue__c;
                milestoneWrapper.totalSalesRevenue =  eachMilestone.OA_Total_Sales_Revenue_Incl_CRs__c;
                milestoneWrapper.riskAdjusted = eachMilestone.OA_Risk_Adjusted__c;
                if(changeRequestMap.containsKey(eachMilestone.OA_Unique_Identifier__c)){
                    List<String> tempList = new List<String>();
                    milestoneWrapper.changeRequests = new List<ChangeWrapper>(); 
                    for(OA_Revenue_Forecast__c crm : changeRequestMap.get(eachMilestone.OA_Unique_Identifier__c)){
                        ChangeWrapper change = new ChangeWrapper();
                        change.crOppId = crm.OA_Opportunity__c;
                        change.crMilestoneId = crm.Id;
                        change.changeAmount = crm.OA_Sales_Revenue__c;
                        change.isClosed = crm.OA_Opportunity__r.StageName == OA_Constant.CLOSEDWON;
                        milestoneWrapper.changeRequests.add(change);
                        tempList.add(String.valueOf(crm.OA_Sales_Revenue__c));
                    }
                    milestoneWrapper.changeAmounts = String.join(tempList, ','); 
                }
                deliveryMilestones.add(milestoneWrapper);
            }else if(eachMilestone.RecordType.DeveloperName.equalsIgnoreCase(OA_Constant.INVOICE)){
                milestoneWrapper.percentageInvoioced = eachMilestone.OA_Percentage_Invoiced__c != null ? eachMilestone.OA_Percentage_Invoiced__c.setScale(2) : 0.0;
                milestoneWrapper.invoiceAmount = eachMilestone.OA_Invoice_Amount__c;
                invoiceMilestones.add(milestoneWrapper);
            }                
        }
        if(deliveryMilestones.size() > 0) haveDeliveryMilestone = true;
        if(invoiceMilestones.size() > 0)  haveInvoiceMilestone = true; 

    }
    
    public class MilestoneWrapper{
        public String sfId{get;set;}
        public String displayMonthYear{get;set;}
        public String comment{get;set;}
        public Decimal salesRevenue{get;set;}
        public Decimal totalSalesRevenue{get;set;}
        public Decimal riskAdjusted{get;set;}
        public String status{get;set;}
        public Decimal percentageInvoioced{get;set;}
        public Decimal invoiceAmount{get;set;}
        public String currencyType{get;set;}
        public String changeAmounts{get;set;}
        public List<ChangeWrapper> changeRequests{get;set;}
    }
    
    public class ChangeWrapper{
        public Id crOppId{get;set;}
        public Id crMilestoneId{get;set;}
        public boolean isClosed{get;set;}
        public String name{get;set;}
        public Decimal changeAmount{get;set;}
    }
}