force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/OA_Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>OA_Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Change Request</relationshipLabel>
    <relationshipName>ChangeRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OA_Rate_Card_Price__c.field-meta.xml
<CustomField>
    <fullName>OA_Rate_Card_Price__c</fullName>
    <description>Field to capture the rate card Cost ONLY. This field will be used for reference purpose only</description>
    <inlineHelpText>Capture the Rate Card Cost without any discount.</inlineHelpText>
    <label>Effort Estimate (EE) Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Change_Request.recordType-meta.xml
<RecordType>
    <fullName>Change_Request</fullName>
    <active>true</active>
    <businessProcess>Change Request</businessProcess>
    <description>Only to Capture Change Request for an Ongoing Project</description>
    <label>Change Request</label>
</RecordType>

force-app/main/default/classes/OA_CreateMilestoneController_Test.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_CreateMilestoneController_Test
Class Purpose: Test class for OA_CreateMilestoneController
Versions: 1.1
******************************************************************************************************/

@isTest
public class OA_CreateMilestoneController_Test {
    
    @isTest
    public static void testCreateMilestoneController(){
        Account testAcc = OA_TestDataUtility.createAccount();
        insert testAcc;
        
        Opportunity testOpp = OA_TestDataUtility.createOpportunity(testAcc);
        testOpp.StageName = 'Proposal';
        insert testOpp;
        
        List<OA_Revenue_Forecast__c> testRF = OA_TestDataUtility.createRevForecast(testOpp);
        insert testRF;
        testOpp.StageName='Closed Won' ;
        testOpp.OA_Rate_Card_Price__c = 2000;
        Update testOpp;
        Opportunity crOpp = OA_TestDataUtility.createOpportunity(testAcc);
        crOpp.RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName = 'Change_Request'].Id;
        crOpp.StageName = 'Proposed';
        crOpp.OA_Parent_Project__c = testOpp.Id;
        insert crOpp;
        
        List<OA_Revenue_Forecast__c> testRFCR = OA_TestDataUtility.createRevForecast(crOpp);
        insert testRFCR;
        
        Test.startTest();
            Test.setCurrentPageReference(new PageReference('Page.OA_CreateMilestone')); 
            System.currentPageReference().getParameters().put('type', 'cr');
        System.currentPageReference().getParameters().put('pid', testOpp.id);
        System.currentPageReference().getParameters().put('crid', crOpp.id);
       
        ApexPages.StandardController sc = new ApexPages.StandardController(testOpp);
        	OA_CreateMilestoneController cms = new  OA_CreateMilestoneController(sc);
        	
        	cms.createMilestones();
        	cms.deleteMilestone();
        	cms.enableEditing();
        	cms.loadMoreRows();
        	cms.togleEmptyRows();
        	cms.renderToOpp();
        	cms.rejectCR();
        	
        Test.stopTest();
        
    }
    
     @isTest
    public static void testCRClose(){
        Account testAcc = OA_TestDataUtility.createAccount();
        insert testAcc;
        
        Opportunity testOpp = OA_TestDataUtility.createOpportunity(testAcc);
        testOpp.StageName = 'Proposed';
        insert testOpp;
        
        List<OA_Revenue_Forecast__c> testRF = OA_TestDataUtility.createRevForecast(testOpp);
        insert testRF;
        
        Opportunity crOpp = OA_TestDataUtility.createOpportunity(testAcc);
        crOpp.RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName = 'Change_Request'].Id;
        crOpp.StageName = 'Proposed';
        crOpp.OA_Parent_Project__c = testOpp.Id;
        insert crOpp;
        
        List<OA_Revenue_Forecast__c> testRFCR = OA_TestDataUtility.createRevForecast(crOpp);
        insert testRFCR;
        
        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(testOpp);
        	OA_CreateMilestoneController cms = new  OA_CreateMilestoneController(sc);
        	cms.createMilestones();
        	cms.deleteMilestone();
        	cms.enableEditing();
        	cms.loadMoreRows();
        	cms.togleEmptyRows();
        	cms.renderToOpp();
        	cms.getMilestoneWrapper();
        	
        Test.stopTest();
        
    }

}