force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/OA_Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>OA_Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Change Request</relationshipLabel>
    <relationshipName>ChangeRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Change_Request.recordType-meta.xml
<RecordType>
    <fullName>Change_Request</fullName>
    <active>true</active>
    <businessProcess>Change Request</businessProcess>
    <description>Only to Capture Change Request for an Ongoing Project</description>
    <label>Change Request</label>
</RecordType>

force-app/main/default/classes/OA_DisplayMilestoneController_Test.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_DisplayMilestoneController_Test
Class Purpose: Test class for OA_DisplayMilestoneController
Versions: 1.1
******************************************************************************************************/

@isTest
public class OA_DisplayMilestoneController_Test {
     @isTest
    public static void testDisplayMilestoneController(){
        Account testAcc = OA_TestDataUtility.createAccount();
        insert testAcc;
        
        Opportunity testOpp = OA_TestDataUtility.createOpportunity(testAcc);
        testOpp.StageName = 'Proposed';
        insert testOpp;
        
        Opportunity crOpp = OA_TestDataUtility.createOpportunity(testAcc);
        crOpp.RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName = 'Change_Request'].Id;
        crOpp.StageName = 'Proposed';
        crOpp.OA_Parent_Project__c = testOpp.Id;
        insert crOpp;
        
        List<OA_Revenue_Forecast__c> testRFCR = OA_TestDataUtility.createRevForecast(crOpp);
        insert testRFCR;
        
        List<OA_Revenue_Forecast__c> testRF = OA_TestDataUtility.createRevForecast(testOpp);
        insert testRF;
        
        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(testOpp);
        	OA_DisplayMilestoneController dmc = new OA_DisplayMilestoneController(sc);
        Test.stopTest();
    }

}