force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Comment__c.field-meta.xml
<CustomField>
    <fullName>OA_Comment__c</fullName>
    <label>Comment</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Forecast_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Forecast_Month__c</fullName>
    <description>Field created for reporting purpose ONLY</description>
    <formula>DATE(VALUE(TEXT(OA_Year__c)), VALUE(TEXT(CASE(OA_Month__c, &quot;1&quot;, 01, &quot;2&quot;, 02, &quot;3&quot;, 03, &quot;4&quot;, 04, &quot;5&quot;, 05, &quot;6&quot;, 06, &quot;7&quot;, 07, &quot;8&quot;, 08, &quot;9&quot;, 09, &quot;10&quot;, 10, &quot;11&quot;, 11, &quot;12&quot;, 12, 0))) ,Value(TEXT(1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Forecast</relationshipLabel>
    <relationshipName>OA_Revenue_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Status__c.field-meta.xml
<CustomField>
    <fullName>OA_Status__c</fullName>
    <description>Status of Delivery and Invoicing Milestones</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Delivery In Progress</fullName>
            </value>
            <value>
                <fullName>Delivery Completed</fullName>
            </value>
            <value>
                <fullName>Invoice Approval Pending</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected</fullName>
            </value>
            <value>
                <fullName>Invoice Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery Milestone</label>
</RecordType>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice Milestone</label>
</RecordType>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_SendDeliveryForecastForApproval_Batch.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_SendDeliveryForecastForApproval_Batch
Class Purpose: Batch to trigger the Approval Process for Revenue Forecast Object records
Versions: 1.2
1.1: Added check for Opportunity status
******************************************************************************************************/
global class OA_SendDeliveryForecastForApproval_Batch implements Database.Batchable<sObject>, Schedulable {
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String month = '\''+ String.valueOf(System.today().month())+ '\'';
        String year  = '\''+ String.valueOf(System.today().year()) + '\'';
        Set<String> allowedStatus = new Set<String>{'Planned','Delivery In Progress'};
        Set<String> oppAllowedStatus = new Set<String>{'Closed Won'};
        String query = 'SELECT CreatedBy.Name, OA_Status__c,OA_Forecast_Month__c, RecordType.Name, RecordType.DeveloperName, OA_Opportunity__c, OA_Comment__c FROM OA_Revenue_Forecast__c WHERE OA_Month__c ='+ month+' AND OA_Year__c ='+ year+' AND OA_Status__c IN : allowedStatus AND OA_Opportunity__r.StageName IN: oppAllowedStatus';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<OA_Revenue_Forecast__c> scope){      
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        for(OA_Revenue_Forecast__c forecast : scope){ 
            if(!Approval.isLocked(forecast)){             
                Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
                approvalRequest.setComments('Submitting request for approval.');
                approvalRequest.setObjectId(forecast.id);            
                if(forecast.RecordType.Name != null && forecast.RecordType.DeveloperName.equalsIgnoreCase(OA_Constant.DELIVERY)) {               
                    approvalRequest.setProcessDefinitionNameOrId('OA_Delivery_Forecast_Approval');
                }
                if(forecast.RecordType.Name != null && forecast.RecordType.DeveloperName.equalsIgnoreCase(OA_Constant.INVOICE)){               
                    approvalRequest.setProcessDefinitionNameOrId('OA_Invoice_Forecast_Approval');
                }
                requests.add(approvalRequest);
            }    
        }        
        try{           
            System.debug('***'+requests);
            Approval.ProcessResult[] processResults = Approval.process(requests, false);
            for(Approval.ProcessResult result: processResults){
                System.debug('result:'+String.valueOf(result.getErrors()));
            }
        }catch(Exception ex){
            System.debug('Exception:'+ex.getMessage());
        }
        
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('Batch Finished');
    }
        
    global void execute(SchedulableContext sc){
        OA_SendDeliveryForecastForApproval_Batch runBatch = new OA_SendDeliveryForecastForApproval_Batch();
        Database.executeBatch(runBatch,1);
    }    
}