force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Forecast</relationshipLabel>
    <relationshipName>OA_Revenue_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Percentage_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>OA_Percentage_Invoiced__c</fullName>
    <label>Percentage Invoiced</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Project_Owner__c.field-meta.xml
<CustomField>
    <fullName>OA_Project_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used in Approval Process, to assign Delivery Forecast for approval.</description>
    <label>Project Owner (Not for layout)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Revenue_Forecast</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>OA_Unique_Identifier__c</fullName>
    <description>This field is updated by workflow. Unique Identifier for milestones. Concatenation of Opportunity Id, RecordTypeId, Month and Year.</description>
    <externalId>true</externalId>
    <label>Unique Identifier(Not for layout)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_RevenueForecastTriggerHandler.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_AccountActivityOverdueCheck_Batch
Class Purpose: Batch to update the Activity Overdue Checkbox on Account Object
Versions: 1.1
******************************************************************************************************/
public class OA_RevenueForecastTriggerHandler {
    
    public static void beforeInsert(List<OA_Revenue_Forecast__c> newlist){
        populateProjectOwner(newlist);        
    }
    
    public static void beforeUpdate(List<OA_Revenue_Forecast__c> newlist, Map<Id, OA_Revenue_Forecast__c> oldMap){
        Integer currentMonth = System.today().month();
        Integer currentYear = System.today().year();
        for(OA_Revenue_Forecast__c forecast :newlist){
            if(forecast.OA_Month__c == null || forecast.OA_Year__c == null) continue;
            OA_Revenue_Forecast__c oldForecast = oldMap.get(forecast.Id);
            if((Integer.valueOf(forecast.OA_Month__c) < currentMonth) && 
               (Integer.valueOf(forecast.OA_Year__c) <= currentYear) && 
               forecast.OA_Percentage_Invoiced__c != oldForecast.OA_Percentage_Invoiced__c){                
                //forecast.addError(Label.Past_due_date_error);
            }
            
            if(forecast.RecordTypeId != oldForecast.RecordTypeId || 
               forecast.OA_Month__c != oldForecast.OA_Month__c ||
               forecast.OA_Year__c != oldForecast.OA_Year__c
              ){
                  populateUniqueIdentifier(forecast);
              }
        }
    }
    
    private static void populateProjectOwner(List<OA_Revenue_Forecast__c> newlist){
        Set<Id> oppIds = new Set<Id>();
        for(OA_Revenue_Forecast__c newForecast : newlist){
            oppIds.add(newForecast.OA_Opportunity__c);
        }
        
        Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>(
            [SELECT Id, OwnerId FROM Opportunity WHERE ID IN : oppIds]
        );
        
        for(OA_Revenue_Forecast__c newForecast : newlist){
            newForecast.OA_Project_Owner__c = opportunities.get(newForecast.OA_Opportunity__c).OwnerId;
            populateUniqueIdentifier(newForecast);            
        }        
    }
    
    private static void populateUniqueIdentifier(OA_Revenue_Forecast__c newForecast){
			
            newForecast.OA_Unique_Identifier__c = String.valueOf(newForecast.OA_Opportunity__c)
                +String.valueOf(newForecast.RecordTypeId)
                +String.valueOf(newForecast.OA_Month__c)
                +String.valueOf(newForecast.OA_Year__c); 
    }
}