force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Comment__c.field-meta.xml
<CustomField>
    <fullName>OA_Comment__c</fullName>
    <label>Comment</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>OA_Invoice_Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Forecast</relationshipLabel>
    <relationshipName>OA_Revenue_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Percentage_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>OA_Percentage_Invoiced__c</fullName>
    <label>Percentage Invoiced</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Revenue_Flow__c.field-meta.xml
<CustomField>
    <fullName>OA_Revenue_Flow__c</fullName>
    <label>Revenue Flow</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Risk_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>OA_Risk_Adjusted__c</fullName>
    <formula>OA_Sales_Revenue__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Risk Adjusted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Sales_Revenue__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Forecasted monthly revenue</description>
    <label>Sales Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Status__c.field-meta.xml
<CustomField>
    <fullName>OA_Status__c</fullName>
    <description>Status of Delivery and Invoicing Milestones</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Delivery In Progress</fullName>
            </value>
            <value>
                <fullName>Delivery Completed</fullName>
            </value>
            <value>
                <fullName>Invoice Approval Pending</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected</fullName>
            </value>
            <value>
                <fullName>Invoice Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>OA_Unique_Identifier__c</fullName>
    <description>This field is updated by workflow. Unique Identifier for milestones. Concatenation of Opportunity Id, RecordTypeId, Month and Year.</description>
    <externalId>true</externalId>
    <label>Unique Identifier(Not for layout)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery Milestone</label>
</RecordType>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice Milestone</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Change_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Request_Type__c</fullName>
    <label>Change Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Timeline Change</fullName>
            </value>
            <value>
                <fullName>Scope Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Project De-Prioritized By Client</fullName>
            </value>
            <value>
                <fullName>Project Cancelled By Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OA_Change_Request_Amount__c.field-meta.xml
<CustomField>
    <fullName>OA_Change_Request_Amount__c</fullName>
    <formula>OA_Parent_Project__r.Amount +  Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Change Request Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OA_CR_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>OA_CR_Submission_Date__c</fullName>
    <label>CR Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OA_Total_Project_Cost__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Project_Cost__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>Total Cost of Won Project along with all Won Change Requests</inlineHelpText>
    <label>Final Price to Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_CreateMilestoneController.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_CreateMilestoneController
Class Purpose: Controller class for Create Milestones page
Versions: 1.1
******************************************************************************************************/
public class OA_CreateMilestoneController {
    
    private Map<Integer, String> monthMap = OA_Utility.getMonthMap();
    private Id oppId;
    public Opportunity currentOpp{get;set;}
    public Map<Integer, MilestoneWrapper> milestones{get;set;}
    public String milestonType{get;set;}
    public Integer currentMonth{get;set;}
    public Integer currentYear{get;set;}
    private Integer rowCount;
    public boolean isValidationFailed{get;set;}
    public boolean displayingEmptyRows{get;set;}
    public boolean isChangeRequest{get;set;}
    public String totalProjectCost{get;set;}
   	private String crOppId;
    public Opportunity crOpp{get;set;}
    public boolean crClosed{get;set;}
    private Set<Id> milestoneAdminIds = new Set<Id>(
        getMilestoneAdmins()
    );
    
    public OA_CreateMilestoneController(ApexPages.StandardController controller){
        Map<String, String> paramMap = ApexPages.currentPage().getParameters();
        if((controller == null || controller.getId() == null) &&  (paramMap == null || !paramMap.containsKey('type'))) return;
        isChangeRequest = false;        
        if(paramMap != null && paramMap.containsKey('type')) isChangeRequest = true;
        oppId = isChangeRequest ? paramMap.get('pid') : controller.getId();
        milestonType = isChangeRequest ?  OA_Constant.INVOICE : OA_Constant.DELIVERY;
        currentOpp = [SELECT id,CurrencyIsoCode,Name,OA_Total_Project_Cost__c, StageName, Amount, Probability FROM Opportunity WHERE Id =: oppId LIMIT 1];        
        currentMonth = SyStem.today().month();
        currentYear =  SyStem.today().year();
        crOppId = isChangeRequest ? paramMap.get('crid') : null;
        if(isChangeRequest){
            crOpp = [Select Amount, Loss_Reason__c ,StageName, Name, OA_CR_Submission_Date__c, Change_Request_Type__c, OA_Change_Request_Amount__c FROM Opportunity WHERE Id =: crOppId];
        }
       
        crClosed = isChangeRequest ? paramMap.get('crs') == OA_Constant.CLOSEDWON  ||  paramMap.get('crs') == 'Closed Lost' : currentOpp.StageName == OA_Constant.CLOSEDWON;
        
        
        if(crClosed) {
            String errorMsg = isChangeRequest ? 'CR is Already '+paramMap.get('crs') : 'Opportunity is Closed won, to make any change create Change Request.';
            OA_Utility.addMessage(errorMsg, 'INFO');
        }
       
        totalProjectCost = isChangeRequest ? String.valueOf(currentOpp.OA_Total_Project_Cost__c + (crClosed ? 0: crOpp.Amount)) : null;
        init();       
    }
    
    
    public void init(){     
        System.debug('milestonType:'+milestonType);        
        isValidationFailed = false;        
        displayingEmptyRows = currentOpp.StageName != OA_Constant.CLOSEDWON ;
        rowCount = currentOpp.StageName != OA_Constant.CLOSEDWON ? 12 : 0;        
        milestones = new Map<Integer, MilestoneWrapper>();
        prepareWrapperMap();
    }
    
    private List<OA_Revenue_Forecast__c> getExistingMilestones(){
        List<OA_Revenue_Forecast__c> oppMilestones = new List<OA_Revenue_Forecast__c>(
            [SELECT Id, CurrencyIsoCode, OA_Comment__c, OA_Opportunity__r.Amount, OA_Invoice_Amount__c, OA_Risk_Adjusted__c , OA_Month__c, OA_Percentage_Invoiced__c, OA_Sales_Revenue__c, OA_Status__c, OA_Year__c
             FROM OA_Revenue_Forecast__c
             WHERE OA_Opportunity__c =: oppId AND RecordType.DeveloperName =: milestonType
            ]
        );		    
        return !oppMilestones.isEmpty() ? oppMilestones : null ;
    }
    
    public void prepareWrapperMap(){
        milestones.putAll(getAdditionalRows());
        //if(currentOpp.StageName != 'Closed Won' ||  milestonType == 'Invoice') milestones.putAll(getAdditionalRows());
        //else {OA_Utility.addMessage('Opportunity is Closed Won. Create chage request to perform any changes with Delivery Milestones. After closing ', 'INFO');}
        List<OA_Revenue_Forecast__c> oppMilestones = getExistingMilestones();
        if(oppMilestones == null) return;
        
        currentOpp.Amount = oppMilestones[0].OA_Opportunity__r.Amount;
        for(OA_Revenue_Forecast__c eachRF : oppMilestones){
            MilestoneWrapper eachRFWrap = new MilestoneWrapper();
            eachRFWrap.month = eachRF.OA_Month__c;
            eachRFWrap.year = eachRF.OA_Year__c;
            eachRFWrap.comment = eachRF.OA_Comment__c;
            eachRFWrap.status = eachRF.OA_Status__c;
            eachRFWrap.sfId = eachRF.Id;
            eachRFWrap.mode = 'v';
            Date cutOffDate = Date.newInstance(
                Integer.valueOf(eachRF.OA_Year__c), 
                Integer.valueOf(eachRF.OA_Month__c)+1, 
                Integer.valueOf(Label.Milestone_Cutoff_Date)
            );
            if(milestonType == OA_Constant.DELIVERY){
                eachRFWrap.riskAdjusted = String.valueOf(eachRF.OA_Risk_Adjusted__c);
                eachRFWrap.revRecognized = String.valueOf(eachRF.OA_Sales_Revenue__c);
            }else if(milestonType == OA_Constant.INVOICE){
                eachRFWrap.percentageInvoioced = String.valueOf(eachRF.OA_Percentage_Invoiced__c != null ? eachRF.OA_Percentage_Invoiced__c.setScale(2) : 0.0);
                eachRFWrap.invoiceAmount =  String.valueOf(eachRF.OA_Invoice_Amount__c);
            }
            eachRFWrap.displayMonthYear = monthMap.get(Integer.valueOf(eachRF.OA_Month__c))+'\''+String.valueOf(eachRF.OA_Year__c).substringAfter('20');
            eachRFWrap.isEditAllowed = eachRFWrap.isDeleteAllowed = TRUE;            
            //if((Integer.valueOf(eachRF.OA_Month__c) < currentMonth &&  Integer.valueOf(eachRF.OA_Year__c) <= currentYear) || crClosed) eachRFWrap.isEditAllowed = eachRFWrap.isDeleteAllowed = FALSE;
            
            if(!milestoneAdminIds.contains(UserInfo.getUserId()) || currentOpp.StageName == OA_Constant.CLOSEDWON || crClosed){
                if(System.today() > cutOffDate || crClosed) eachRFWrap.isEditAllowed = eachRFWrap.isDeleteAllowed = FALSE;
                if(currentOpp.StageName == OA_Constant.CLOSEDWON) eachRFWrap.isDeleteAllowed = FALSE;
            }
            eachRFWrap.mapKey = Integer.valueOf(eachRF.OA_Month__c) + Integer.valueOf(eachRF.OA_Year__c)*100;
            milestones.put(eachRFWrap.mapKey, eachRFWrap);           
        }
    }
    
    
    
    public Map<Integer, MilestoneWrapper> getAdditionalRows(){
       
        Map<Integer, MilestoneWrapper> additionalEmptyRows = new Map<Integer, MilestoneWrapper>();
        String displayMonthYear = '';
        integer tempMonth = milestoneAdminIds.contains(UserInfo.getUserId()) ? 1 : currentMonth;
        integer tempYear = currentYear ;        
        for(Integer i=1; i<=rowCount; i++){            
            if(tempMonth > 12){
                tempMonth = 1;
                tempYear += 1;
            }
            if(!milestones.containsKey(tempMonth+tempYear*100)){ 
                displayMonthYear = monthMap.get(tempMonth)+'\''+String.valueOf(tempYear).substringAfter('20');
                MilestoneWrapper additionalWrap =  new MilestoneWrapper();
                additionalWrap.month = String.valueOf(tempMonth);
                additionalWrap.year = String.valueOf(tempYear);
                additionalWrap.displayMonthYear = displayMonthYear;
                additionalWrap.mode = 'e';
                additionalWrap.isEditAllowed = additionalWrap.isDeleteAllowed = False;
                additionalWrap.status = 'Planned';
                
                additionalEmptyRows.put(tempMonth+tempYear*100, additionalWrap);   
                
            }
            tempMonth ++;
        }         
        System.debug('additionalEmptyRows:'+additionalEmptyRows.size());
        return additionalEmptyRows;
    }
    
    
    public PageReference createMilestones(){
        Decimal milestonesSum = 0;
        String close = ApexPages.currentPage().getParameters().get('close');
        List<OA_Revenue_Forecast__c> revForecastList = new List<OA_Revenue_Forecast__c>();       
        Map<String, String> recordTypeMap = OA_Utility.getRecordTypeInfosByName(OA_Constant.REVENUEFORECASTAPINAME);
        String externalId = '';
        for(MilestoneWrapper eachWrap : milestones.values()){
            if(milestonType ==  OA_Constant.DELIVERY && ! validateDecimalValue(eachWrap.revRecognized)) continue;
            if(milestonType ==  OA_Constant.INVOICE  && ! validateDecimalValue(eachWrap.invoiceAmount)) continue;
            if(isValidationFailed) return null;
            externalId = String.valueOf(oppId)+recordTypeMap.get(milestonType)+eachWrap.month+eachWrap.year;
            OA_Revenue_Forecast__c revForecast = new OA_Revenue_Forecast__c();
            revForecast.OA_Unique_Identifier__c = externalId;
            revForecast.OA_Month__c = eachWrap.month;
            revForecast.OA_Year__c = eachWrap.year;
            revForecast.OA_Comment__c = eachWrap.comment;
            revForecast.RecordTypeId = recordTypeMap.get(milestonType);
            revForecast.OA_Opportunity__c = oppId;
            revForecast.OA_Status__c = eachWrap.status; 
            revForecast.CurrencyIsoCode = currentOpp.CurrencyIsoCode;
            revForecast.OA_Revenue_Flow__c = Integer.valueOf(eachWrap.year) == System.today().year() ? 'C' : Integer.valueOf(eachWrap.year) < System.today().year() ? 'P' : 'F';
            if(milestonType ==  OA_Constant.DELIVERY){
                revForecast.OA_Sales_Revenue__c = Decimal.valueOf(eachWrap.revRecognized);
                milestonesSum += revForecast.OA_Sales_Revenue__c;
            }
            if(milestonType ==  OA_Constant.INVOICE){
                revForecast.OA_Invoice_Amount__c  = Decimal.valueOf(eachWrap.invoiceAmount);
                revForecast.OA_Percentage_Invoiced__c = (revForecast.OA_Invoice_Amount__c*100)/currentOpp.Amount; 
                milestonesSum += revForecast.OA_Invoice_Amount__c;
            }
            revForecastList.add(revForecast);                     
        }
        if(milestonType ==  OA_Constant.INVOICE){
            if(currentOpp.StageName != OA_Constant.CLOSEDWON && milestonesSum > currentOpp.Amount){                
                OA_Utility.addMessage(Label.Invoice_Milestone_Sum_greater_than_100, 'ERROR');
                return null;
            }
            if(!isChangeRequest && currentOpp.StageName == OA_Constant.CLOSEDWON && milestonesSum != currentOpp.OA_Total_Project_Cost__c){
                OA_Utility.addMessage(Label.Invoice_Amount_Opp_Closed_Won_and_Invoice_Milestone_not_equals_to_100, 'ERROR');
                return null;
            }
            if(isChangeRequest && milestonesSum != Decimal.valueOf(totalProjectCost)){
                OA_Utility.addMessage('Invoice amount should be equal to close CR', 'ERROR');
                return null;
            }
        }
        if(milestonType ==  OA_Constant.DELIVERY){
            /*if(milestonesSum > currentOpp.Amount){
                OA_Utility.addMessage(Label.Delivery_Milestone_Sum_greater_than_Opportunity_Amount, 'ERROR');
                return null;
            }*/
            if(currentOpp.StageName == OA_Constant.CLOSEDWON  && milestonesSum <> currentOpp.Amount){
                OA_Utility.addMessage(Label.Delivery_Milestone_Opp_Closed_Won_and_Sum_not_equals_to_Opportunity_Amount, 'ERROR');
                return null;
            }            
        }
        
        
        if(!revForecastList.isEmpty()){
            OA_Utility.handleUpsertResult(
                Database.upsert(revForecastList, Schema.OA_Revenue_Forecast__c.OA_Unique_Identifier__c, FALSE)
            );
        }
        if(isChangeRequest){
            Opportunity crOpp = new Opportunity(Id= crOppId, StageName = 'Closed Won');
            Database.SaveResult sr = Database.update(crOpp);
            if(!sr.isSuccess()) return null;  
            OA_Utility.addMessage('CR closed successfully', 'CONFIRM');
            crClosed = TRUE;
        }
        if(close != null && close != '' && close == 'yes') return renderToOpp();
        
        prepareWrapperMap();
        
        return null;
    }
    
    private boolean validateDecimalValue(String strValue){        
        try{
            Decimal.valueOf(strValue);
            isValidationFailed = false;
            return true; 
        } catch (Exception e) {
            if(strValue != null && strValue != '')
                OA_Utility.addMessage(Label.Valid_Revenue_Recognized_and_Invoiced_Percentage, 'ERROR');
            isValidationFailed = true;
            return FALSE;
        }        
    }
    
    public void enableEditing(){
        MilestoneWrapper m = getMilestoneWrapper();
        if(m == null) return;
        m.mode = 'e';
        m.isEditAllowed = FALSE;    
    }
    
    public void deleteMilestone(){
        MilestoneWrapper m = getMilestoneWrapper();
        if(m == null) return;
        milestones.remove(m.mapKey);
        OA_Revenue_Forecast__c rf = new OA_Revenue_Forecast__c(Id = m.sfId);
        delete rf;
    }
    
    public void rejectCR(){
        if(crOpp.Loss_Reason__c == NULL || crOpp.Loss_Reason__c == '' || crOpp.Loss_Reason__c == '--NONE--'){
            OA_Utility.addMessage('Please Select Loss Reason before Rejecting CR.', 'ERROR');
            return;
        }
        crOpp.StageName = 'Closed Lost';
        crClosed = true;
        OA_Utility.addMessage('CR Rjected Successfully.', 'CONFIRM');
        update crOpp;
        
    }
    
    public void loadMoreRows(){
        rowCount += 6;
        milestones.putAll(getAdditionalRows());
    }
    
    public void togleEmptyRows(){
        milestones.clear();
        if(displayingEmptyRows){
            displayingEmptyRows = false;
            rowCount = 0;
        }
        else {
            displayingEmptyRows = true;
            rowCount = 12;
        }
        prepareWrapperMap();
    }
    
    public PageReference renderToOpp(){
        PageReference pageRef = new PageReference('/'+oppId);
        return pageRef;
    }
    
    public MilestoneWrapper getMilestoneWrapper(){
        String key = ApexPages.currentPage().getParameters().get('key');
        if(key == null || key == '' || !key.isNumeric() || !milestones.containsKey(Integer.valueOf(key))){
            OA_Utility.addMessage(Label.Generic_Error_Message, 'FATAL'); 
            return null;
        }       
        return milestones.get(Integer.valueOf(key));        
    }
    
    private set<id> getMilestoneAdmins(){
        Set<Id> milestoneAdminIds = new Set<Id>();       
        for(GroupMember gm : [SELECT Id, UserOrGroupId, Group.Name FROM GroupMember WHERE Group.DeveloperName = 'Milestone_Admin']){
            milestoneAdminIds.add(gm.UserOrGroupId);
        }
        return milestoneAdminIds;
    }

    public class MilestoneWrapper{
        public Id sfId{get;set;}
        public Integer mapKey{get;set;}
        public String month{get;set;}
        public String year{get;set;}
        public boolean isEditAllowed{get;set;}
        public boolean isDeleteAllowed{get;set;}
        public String mode{get;set;}
        public String displayMonthYear{get;set;}
        public String comment{get;set;}
        public String revRecognized{get;set;}
        public String riskAdjusted{get;set;}
        public String status{get;set;}
        public String percentageInvoioced{get;set;}
        public String invoiceAmount{get;set;} 
    }
    
}