force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/OA_Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>OA_Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Change Request</relationshipLabel>
    <relationshipName>ChangeRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Change_Request.recordType-meta.xml
<RecordType>
    <fullName>Change_Request</fullName>
    <active>true</active>
    <businessProcess>Change Request</businessProcess>
    <description>Only to Capture Change Request for an Ongoing Project</description>
    <label>Change Request</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <businessProcess>Project</businessProcess>
    <description>Default Record Type, to capture all Opportunities (Prospective Projects)</description>
    <label>Project</label>
</RecordType>

force-app/main/default/classes/OA_TestOpportunityTrigger.cls
@isTest
public class OA_TestOpportunityTrigger {
    
    @testSetUp
    public static void insertTestData(){
        Account a = OA_TestDataUtility.createAccount();
        insert a;
        
        Opportunity o = OA_TestDataUtility.createOpportunity(a);
        o.StageName = 'Proposal';
        insert o;
        
        Opportunity cr = OA_TestDataUtility.createOpportunity(a);
        cr.StageName = 'Proposal';
        cr.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Change Request'].Id;
        cr.OA_Parent_Project__c = o.Id;
        insert cr;
        
        List<OA_Revenue_Forecast__c> rfList = OA_TestDataUtility.createRevForecast(o);
        insert rfList;
        
        List<OA_Revenue_Forecast__c> crRFList = OA_TestDataUtility.createRevForecast(cr);
        insert crRFList;
    }
    
    @isTest
    public static void testProjectClosedWon(){
        Opportunity o = [Select Id, StageName FROM Opportunity WHERE RecordType.DeveloperName = 'Project' LIMIT 1];
        Test.startTest();
        o.StageName =  'Closed Won';
        boolean isError = false;
        try{
            update o;
        }Catch(Exception e){
            isError = true;
        }
        System.assert(isError);
        Test.stopTest();
    }
    
     @isTest
    public static void testInvoiceCalculation(){
        Opportunity o = [Select Id, StageName FROM Opportunity WHERE RecordType.DeveloperName = 'Project' LIMIT 1];
        Test.startTest();
        o.Amount =  1000;
        update o;
        Test.stopTest();
    }
    
    @isTest
    public static void testCRClosedWon(){
        Opportunity o = [Select Id, StageName FROM Opportunity WHERE RecordType.DeveloperName = 'Change_Request' LIMIT 1];
        Test.startTest();
        o.StageName =  'Closed Won';       
        update o;
        Test.stopTest();
        
        o.Name = 'Change Name';
        boolean isError = false;
        try{
            update o;
        }Catch(Exception e){
            isError = true;
        }
        
        //System.assert(isError);
        
        isError = false;
        try{
            delete o;
        }Catch(Exception e){
            isError = true;
        }
        
        //System.assert(isError);
        
    }

}