force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <formula>January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_BR_NetSoldAdditionCntrl.cls
public class OA_BR_NetSoldAdditionCntrl {
    
    
    public string selectedRegion{get;set;}
    public string selectedFromMonth{get;set;}
    public string selectedToMonth{get;set;}
    public string selectedFromYear{get;set;} 
    public string selectedToYear{get;set;} 
    public List<SelectOption> regions{get;set;}
    public List<SelectOption> months{get;set;}
    public List<SelectOption> years{get;set;}
    public List<ReportData> reportDataList{get;set;}
    
    public Decimal totalSoldTillFrom{get;set;}
    public Decimal totalSoldTillTo{get;set;}
    
    public OA_BR_NetSoldAdditionCntrl(){
        init();
    }
    
    public void init(){
        regions = OA_ReportUtility.getRegionList();
        years = OA_ReportUtility.getYearList();
        months = OA_ReportUtility.getMonthList();
        selectedRegion = 'Global';
        selectedToMonth  = String.valueOf(System.today().month()-1);
        selectedFromMonth = String.valueOf(System.today().month()-2);
        selectedFromYear   = String.valueOf(System.today().year());  
        selectedToYear   = String.valueOf(System.today().year()); 
        prepareReportData();
    }
    
    public void prepareReportData(){
        reportDataList = new List<ReportData>();
        totalSoldTillFrom = 0;
        totalSoldTillTo = 0;
        try{
           
            List<AggregateResult> sold_till_from = new List<AggregateResult>(
                (List<AggregateResult>)Database.query(getQuery(selectedFromMonth,selectedFromYear,selectedRegion))
            );
            List<AggregateResult> sold_till_to = new List<AggregateResult>(
                (List<AggregateResult>)Database.query(getQuery(selectedToMonth,selectedToYear,selectedRegion))
            );
            
            Map<String,Decimal> soldTillFromMap = getFormattedMap(sold_till_from);
            Map<String,Decimal> soldTillToMap = getFormattedMap(sold_till_to);
            
            Set<String> accNames = new Set<String>(soldTillFromMap.keyset());
            accNames.addAll(soldTillToMap.keyset());
            
            for(String accName : accNames){
                ReportData data = new ReportData();
                data.AccountName = accName;
                if(soldTillFromMap.containsKey(accName)){
                    data.SodlTillFromMonth = (soldTillFromMap.get(accName)/1000).setscale(2);
                    totalSoldTillFrom += soldTillFromMap.get(accName);
                } else data.SodlTillFromMonth = 0;
                if(soldTillToMap.containsKey(accName)){
                    data.SodlTillToMonth = (soldTillToMap.get(accName)/1000).setscale(2);
                    totalSoldTillTo +=soldTillToMap.get(accName);
                } else data.SodlTillToMonth = 0;
                data.NetAddition = data.SodlTillToMonth - data.SodlTillFromMonth;
                reportDataList.add(data);
            }
            reportDataList.add(new ReportData());
            ReportData totalRow = new ReportData();
            totalRow.Region = 'Global';
            totalRow.AccountName = 'Total';
            totalRow.SodlTillFromMonth = (totalSoldTillFrom/1000).setscale(2);
            totalRow.SodlTillToMonth = (totalSoldTillTo/1000).setscale(2);
            totalRow.NetAddition =  totalRow.SodlTillToMonth - totalRow.SodlTillFromMonth;
            reportDataList.add(totalRow);
        }Catch(Exception e){
            System.debug('Exception: '+e.getStackTraceString());
            OA_Utility.addMessage('Did not found correct data for selected criteria. Please change the criteria and try again.', 'Info');
        }
        
    }
    private Map<String, Decimal> getFormattedMap(List<AggregateResult> results){
        if(results == null || results.isEmpty()) return null;
        Map<String, Decimal> formattedMap = new Map<String, Decimal>();
        for(AggregateResult ar : results){
            // if(selectedRegion != 'Global' && selectedRegion != (String)ar.get('OA_Region__c')) continue;
            formattedMap.put(
                (String)ar.get('Account_Name__c'),
                (Double)ar.get('expr0')
            );            
        }
        return formattedMap;
    }
    
    private String getQuery( String month,String year, String region){
        String baseQuery = 'Select Account_Name__c, SUM(Gross__c) FROM OA_Data_Snapshots__c ';
        String whereClouse = 'WHERE OA_Year__c=\''+ year+'\' AND Snapshot_Month__c =\''+month+'\' AND OA_Probability__c = 100 ';
        if(region != 'Global'){
            whereClouse += ' AND OA_Region__c=\''+region+'\'';
        }
        String groupBy = ' Group By Account_Name__c';
        String orderBy = ' ORDER BY SUM(Gross__c) DESC';
        String query = baseQuery+ whereClouse+groupBy+orderBy;
        System.debug('finalQuery'+query);
        return query;
    }
    
    public class ReportData{
        public String Region{get;set;}
        public String AccountName{get;set;}
        public Decimal SodlTillFromMonth{get;set;}
        public Decimal SodlTillToMonth{get;set;}
        public Decimal NetAddition{get;set;}
    }
    
}