force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <formula>January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Opportunity_Rep__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Data_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Risk_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>Risk_Adjusted__c</fullName>
    <formula>(January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c ) * OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Risk Adjusted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_BR_WeightedGrossPipelineCntrl.cls
public class OA_BR_WeightedGrossPipelineCntrl {
    
    public string eastCoatsProbability{get;set;}
    public string westCoatsProbability{get;set;}
    public string europeProbability{get;set;}
    public string apacProbability{get;set;}
    public String selectedYear{get;set;}
    public String selectedMonth{get;set;}
    public List<SelectOption> months{get;set;}
    public List<SelectOption> years{get;set;}
    public List<ReportData> dataList{get;set;}
    
    public OA_BR_WeightedGrossPipelineCntrl(){
        init();
    }
    
    public void init(){
        eastCoatsProbability = '70';
        westCoatsProbability = '70';
        europeProbability = '70';
        apacProbability = '70';
        years = OA_ReportUtility.getYearList();
        months = OA_ReportUtility.getMonthList();    
        selectedMonth  = String.valueOf(System.today().month()-1);
        selectedYear   = String.valueOf(System.today().year());
        prepareReportData();
    }
    
    public void prepareReportData(){
        if(!isDecimal(eastCoatsProbability) 
           || !isDecimal(westCoatsProbability)
           || !isDecimal(europeProbability)
           || !isDecimal(apacProbability)
          )return;
        dataList = new List<ReportData>();
        try{
            if(Integer.valueOf(selectedYear) == System.today().year() &&
               (Integer.valueOf(selectedMonth) > System.today().month() ))
            {
                OA_Utility.addMessage('Snapshot month must not be greater than the current month for year: '+selectedYear, 'Info');
                return;
            }
            
            List<OA_Data_Snapshots__c> snapshots = new List<OA_Data_Snapshots__c>(
                [Select OA_Region__c,OA_Probability__c, Opportunity_Rep__r.Name, Account_Name__c, Opportunity_Name__c, Gross__c, Risk_Adjusted__c 
                 FROM OA_Data_Snapshots__c
                 WHERE ((OA_Region__c= 'East Coast US' AND OA_Probability__c >=: Decimal.valueOf(eastCoatsProbability)) OR (OA_Region__c=:'West Coast US' AND OA_Probability__c >=:Decimal.valueOf(westCoatsProbability)) OR (OA_Region__c=:'Europe' AND OA_Probability__c >=:Decimal.valueOf(europeProbability)) OR (OA_Region__c=:'APAC & MEA' AND OA_Probability__c >=:Decimal.valueOf(apacProbability))) AND OA_Year__c=:selectedYear AND Snapshot_Month__c=:selectedMonth AND OA_Probability__c < 100
                 Order By OA_Region__c
                ]
            );
            
            if(snapshots.size() == 0){
                OA_Utility.addMessage('Snapshot not captured for selected month and year.', 'Info');
                return;
            }
            
            for(OA_Data_Snapshots__c data : snapshots){
                ReportData rData = new ReportData(
                    data.OA_Region__c,
                    data.Opportunity_Rep__r.Name,
                    data.Account_Name__c,
                    data.Opportunity_Name__c,
                    data.Risk_Adjusted__c,
                    data.Gross__c,
                    data.OA_Probability__c
                );
                dataList.add(rData);
            }
            
            List<AggregateResult> subTotal = new List<AggregateResult>(
                [Select SUM(Gross__c), SUM(Risk_Adjusted__c) 
                 FROM OA_Data_Snapshots__c
                 WHERE ((OA_Region__c= 'East Coast US' AND OA_Probability__c >=: Decimal.valueOf(eastCoatsProbability)) OR (OA_Region__c=:'West Coast US' AND OA_Probability__c >=:Decimal.valueOf(westCoatsProbability)) OR (OA_Region__c=:'Europe' AND OA_Probability__c >=:Decimal.valueOf(europeProbability)) OR (OA_Region__c=:'APAC & MEA' AND OA_Probability__c >=:Decimal.valueOf(apacProbability))) AND OA_Year__c=:selectedYear AND Snapshot_Month__c=:selectedMonth AND OA_Probability__c < 100
                ]
            );
            
            List<AggregateResult> others = new List<AggregateResult>(
                [Select SUM(Gross__c), SUM(Risk_Adjusted__c)
                 FROM OA_Data_Snapshots__c
                 WHERE ((OA_Region__c= 'East Coast US' AND OA_Probability__c <: Decimal.valueOf(eastCoatsProbability)) OR (OA_Region__c=:'West Coast US' AND OA_Probability__c <:Decimal.valueOf(westCoatsProbability)) OR (OA_Region__c=:'Europe' AND OA_Probability__c <:Decimal.valueOf(europeProbability)) OR (OA_Region__c=:'APAC & MEA' AND OA_Probability__c <:Decimal.valueOf(apacProbability))) AND OA_Year__c=:selectedYear AND Snapshot_Month__c=:selectedMonth
                ]
            );
            dataList.add(new ReportData('','','','', null, null, null));
            ReportData subtotalRow = new ReportData('Subtotal','','','', 
                                                    (Decimal)subTotal[0].get('expr1'), 
                                                    (Decimal)subTotal[0].get('expr0'), 
                                                    ((Decimal)subTotal[0].get('expr1')/(Decimal)subTotal[0].get('expr0'))*100
                                                   );
            dataList.add(subtotalRow);
            
            dataList.add(new ReportData('','','','', null, null, null));
            ReportData othersRow = new ReportData('Others','','','', 
                                                  (Decimal)others[0].get('expr1'), 
                                                  (Decimal)others[0].get('expr0'),
                                                  ((Decimal)others[0].get('expr1')/(Decimal)others[0].get('expr0'))*100                                    
                                                 );
            dataList.add(othersRow);                   
            dataList.add(new ReportData('','','','', null, null, null));
            dataList.add(new ReportData('Total','','','', 
                                        (Decimal)subTotal[0].get('expr1') + (Decimal)others[0].get('expr1'), 
                                        (Decimal)subTotal[0].get('expr0') + (Decimal)others[0].get('expr0'), 
                                        ((subtotalRow.WPipeline + othersRow.WPipeline)/(subtotalRow.GPipeline + othersRow.GPipeline))*100
                                       )); 
        }Catch(Exception ex){
            OA_Utility.addMessage(ex.getMessage(), 'Error');
        }
        
    }
    
    public boolean isDecimal(String probability){
        try{
            Decimal.valueOf(probability);
            return true;
        }Catch(Exception e){
            return false;
        }
    }
    
    
    public class ReportData{
        public String Region{get;set;}
        public String Rep{get;set;}
        public String AccountName{get;set;}
        public String OpportunityName{get;set;}
        public Decimal WPipeline{get;set;}
        public Decimal GPipeline{get;set;}
        public Decimal Probability{get;set;}
        
        public ReportData(String Region, String Rep, String accName, String oppName, Decimal WP, Decimal GP, Decimal P){
            this.Region = Region;
            this.Rep = Rep;
            this.AccountName = accName;
            this.OpportunityName = oppName;
            this.WPipeline = WP;
            this.GPipeline = GP;
            this.Probability = P != null ? P.setScale(2) : null;
        }
    }
    
}