force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/April_Weighted__c.field-meta.xml
<CustomField>
    <fullName>April_Weighted__c</fullName>
    <formula>April__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>April Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <label>August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/August_Weighted__c.field-meta.xml
<CustomField>
    <fullName>August_Weighted__c</fullName>
    <formula>OA_Probability__c * August__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>August Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <label>December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/December_Weighted__c.field-meta.xml
<CustomField>
    <fullName>December_Weighted__c</fullName>
    <formula>OA_Probability__c *  December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>December Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/February_Weighted__c.field-meta.xml
<CustomField>
    <fullName>February_Weighted__c</fullName>
    <formula>February__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>February Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/January_Weighted__c.field-meta.xml
<CustomField>
    <fullName>January_Weighted__c</fullName>
    <formula>January__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>January Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/July_Weighted__c.field-meta.xml
<CustomField>
    <fullName>July_Weighted__c</fullName>
    <formula>OA_Probability__c *  July__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>July Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/June_Weighted__c.field-meta.xml
<CustomField>
    <fullName>June_Weighted__c</fullName>
    <formula>OA_Probability__c *  June__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>June Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/March_Weighted__c.field-meta.xml
<CustomField>
    <fullName>March_Weighted__c</fullName>
    <formula>March__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>March Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/May_Weighted__c.field-meta.xml
<CustomField>
    <fullName>May_Weighted__c</fullName>
    <formula>May__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>May Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <label>November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/November_Weighted__c.field-meta.xml
<CustomField>
    <fullName>November_Weighted__c</fullName>
    <formula>OA_Probability__c * November__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>November Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <label>October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/October_Weighted__c.field-meta.xml
<CustomField>
    <fullName>October_Weighted__c</fullName>
    <formula>OA_Probability__c *  October__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>October Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/September_Weighted__c.field-meta.xml
<CustomField>
    <fullName>September_Weighted__c</fullName>
    <formula>September__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>September Weighted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_BR_BudgetSalesForecastCntrl.cls
public class OA_BR_BudgetSalesForecastCntrl {  
    Set<String> monthSet = new Set<String>();    
    Map<String, String> monthMap = OA_ReportUtility.getMonthMap();
    public List<ReportData> dataList{get;set;}
    public String selectedYear{get;set;}
    public String selectedMonth{get;set;}
    public String snapshotMonth{get;set;}
    public String selectedRegion{get;set;}
    public List<SelectOption> years{get;set;}
    public List<SelectOption> months{get;set;}
    public List<SelectOption> regionList{get;set;}
    
    public OA_BR_BudgetSalesForecastCntrl(){
        
        years = OA_ReportUtility.getYearList();
        months = OA_ReportUtility.getMonthList();
        selectedRegion = 'Global';
        selectedMonth = String.valueOf(Date.today().month());
        snapshotMonth = String.valueOf(Date.today().month()-1);
        selectedYear = String.valueOf(Date.today().year());
        regionList = OA_ReportUtility.getRegionList();
        
        
        reportTableData();
    }   
    
  
    
    public void reportTableData(){ 
        dataList = new List<ReportData>();               
        Map<String,Map<String, Decimal>> budgetMap = new Map<String,Map<String, Decimal>>();
        Map<String,Map<String, Decimal>> forecastMap = new Map<String,Map<String, Decimal>>();
        Map<String,Map<String, Decimal>> soldMap = new Map<String,Map<String, Decimal>>();
        Map<String,Map<String, Decimal>> pipelineMap = new Map<String,Map<String, Decimal>>();
        String key = '';
        try{
            Set<String> regionSet = new Set<String>{selectedRegion};            
            if(selectedRegion == 'Global'){
                for(SelectOption region : regionList){
                    regionSet.add(region.getValue());
                }
            }
            if(Integer.valueOf(selectedYear) == System.today().year() &&
               (Integer.valueOf(snapshotMonth) > System.today().month() ))
            {
                OA_Utility.addMessage('Snapshot month must not be greater than the current month for year: '+selectedYear, 'Info');
                return;
            }
            budgetMap = OA_ReportUtility.getRegionlQuotaByMonth(selectedYear);
            monthSet = new Set<String>();
            if(Integer.valueOf(snapshotMonth) <= 12) monthSet.add(String.valueOf(Integer.valueOf(snapshotMonth)));
            
            if(Integer.valueOf(snapshotMonth)+1 <= 12) monthSet.add(String.valueOf(Integer.valueOf(snapshotMonth)+1));
            if(Integer.valueOf(snapshotMonth)+2 <= 12) monthSet.add(String.valueOf(Integer.valueOf(snapshotMonth)+2));
            if(Integer.valueOf(snapshotMonth)+3 <= 12) monthSet.add(String.valueOf(Integer.valueOf(snapshotMonth)+3));
          
            
            List<AggregateResult> sold = new List<AggregateResult>(
                [Select OA_Region__c reg, Sum(January__c), Sum(February__c), Sum(March__c),Sum(April__c),Sum(May__c),Sum(June__c),Sum(July__c),Sum(August__c),Sum(September__c),Sum(October__c),Sum(November__c),Sum(December__c) 
                 FROM OA_Data_Snapshots__c 
                 WHERE OA_Region__c IN: regionSet AND OA_Year__c=: selectedYear AND Snapshot_Month__c =: snapshotMonth AND OA_Probability__c = 100 
                 Group by Rollup(OA_Region__c)
                ]            
            );
            if(sold.size() == 0){
                OA_Utility.addMessage('Snapshot not captured for selected month and year.', 'Info');
                return;
            }
            for(AggregateResult ar : sold){
                key = String.valueOf(ar.get('reg'));
                if(!soldMap.containsKey(key)) soldMap.put(key, new Map<String, Decimal>());
                for(String month : monthSet){
                    if(Integer.valueOf(month) > 12 ) continue;
                    String expr = 'expr'+String.valueOf(Integer.valueOf(month) -1);
                    soldMap.get(key).put(month, (Decimal)ar.get(expr));
                }                       
            }        
            
            List<AggregateResult> pipeline = new List<AggregateResult>(
                [Select OA_Region__c reg, Sum(January_Weighted__c), Sum(February_Weighted__c), Sum(March_Weighted__c),Sum(April_Weighted__c),Sum(May_Weighted__c),Sum(June_Weighted__c),Sum(July_Weighted__c),Sum(August_Weighted__c),Sum(September_Weighted__c),Sum(October_Weighted__c),Sum(November_Weighted__c),Sum(December_Weighted__c) 
                 FROM OA_Data_Snapshots__c 
                 WHERE OA_Region__c IN: regionSet AND OA_Year__c=: selectedYear AND Snapshot_Month__c =: snapshotMonth AND OA_Probability__c < 100 
                 Group by Rollup(OA_Region__c)
                ]  
            );
            
            for(AggregateResult ar : pipeline){
                key = String.valueOf(ar.get('reg'));
                if(!pipelineMap.containsKey(key)) pipelineMap.put(key, new Map<String, Decimal>());
                for(String month : monthSet){
                    if(Integer.valueOf(month) > 12 ) continue;
                    String expr = 'expr'+String.valueOf(Integer.valueOf(month) -1);
                    pipelineMap.get(key).put(month, (Decimal)ar.get(expr));
                }                       
            }
            for(String month : monthSet){                
                ReportData totalRow = new ReportData();
                totalRow.Region = 'Global';
                totalRow.Month  = monthMap.get(month);                
                for(String region  : regionSet){                    
                    if(region == 'Global') continue;                    
                    if(Integer.valueOf(month) > 12 ) continue;
                    ReportData data = new ReportData();
                    data.region = region;
                    data.month = monthMap.get(month);
                    if(budgetMap.containsKey(region) && budgetMap.get(region).containsKey(monthMap.get(month))){
                        data.budget = (budgetMap.get(region).get(monthMap.get(month))/1000).setScale(1);
                        totalRow.budget += data.budget;
                    }else data.budget = 0;
                    /*if(forecastMap.containsKey(region) && forecastMap.get(region).containsKey(month)){
                        data.forecast = (forecastMap.get(region).get(month)/1000).setScale(1);
                    }else data.forecast = 0;*/
                    if(soldMap.containsKey(region) && soldMap.get(region).containsKey(month)){
                        data.sold = (soldMap.get(region).get(month)/1000).setScale(1);
                        totalRow.sold += data.sold;
                    }else data.sold = 0;
                    if(pipelineMap.containsKey(region) && pipelineMap.get(region).containsKey(month)){
                        data.pipeline = pipelineMap.get(region).get(month);
                        totalRow.pipeline += data.pipeline;
                    }else data.pipeline = 0;
                      
                    if(data.sold > data.budget){
                        data.surplus = data.sold - data.budget;
                        data.yettobeIdentified = 0;   
                        data.totalSold = data.sold;
                        data.sold = data.budget;
                    }else{
                         data.surplus = data.sold - data.budget;
                        data.totalSold = data.sold;
                        data.yettobeIdentified = data.budget - data.sold - data.pipeline; 
                        if(data.yettobeIdentified < 0){
                            data.yettobeIdentified = 0;
                        }
                    }
                    data.forecast = data.totalSold + data.pipeline;
                      data.Variance =data.forecast-data.budget;
                    dataList.add(data);
                }
                if(totalRow.sold > totalRow.budget){
                    totalRow.surplus = totalRow.sold - totalRow.budget;
                    totalRow.yettobeIdentified = 0;   
                    totalRow.totalSold = totalRow.sold;
                    totalRow.sold = totalRow.budget;
                }else{
                    totalRow.surplus = totalRow.sold - totalRow.budget;
                    totalRow.totalSold = totalRow.sold;
                    totalRow.yettobeIdentified = totalRow.budget - totalRow.sold - totalRow.pipeline; 
                    if(totalRow.yettobeIdentified < 0){
                        totalRow.yettobeIdentified = 0;
                    }
                }
                totalRow.forecast = totalRow.totalSold + totalRow.pipeline;
                totalRow.Variance =totalRow.forecast-totalRow.budget;
                if(selectedRegion == 'Global')dataList.add(totalRow);
                
            }
        }Catch(Exception e){
            OA_Utility.addMessage('Something went wrong, contact your system admin.', 'ERROR');
            System.debug('Error:'+e.getMessage() +'\n'+e.getStackTraceString());
        }
    }  
    
    public class ReportData{
        public String region{get;set;}
        public String month{get;set;}
        public Decimal budget{get;set;}
        public Decimal sold{get;set;}
        public Decimal totalSold{get;set;}
        public Decimal surplus{get;set;}
        public Decimal pipeline{get;set;}
        public Decimal forecast{get;set;}
        public Decimal yettobeIdentified{get;set;}
         public Decimal Variance{get;set;}
        public ReportData(){
            budget = 0.0;
            sold = 0.0;
            totalSold = 0.0;
            surplus = 0.0;
            pipeline = 0.0;
            forecast = 0.0;
            yettobeIdentified = 0.0;
        }
    }
}