force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/Sales_Quota__c.object-meta.xml
<CustomObject>
    <label>Sales Quota</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Sales Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
                <isActive>false</isActive>
                <label>Global</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OA_BR_WeightedGrossPipelineCntrl_Test.cls
@isTest
public class OA_BR_WeightedGrossPipelineCntrl_Test {
 public static testMethod void testReportData(){
        Account a = OA_TestDataUtility.createAccount();
        insert a;
        Sales_Quota__c sq = OA_TestDataUtility.createRegionalSalesQuota();
        insert sq;
        List<OA_Data_Snapshots__c> dataSnapList = new List<OA_Data_Snapshots__c>();
        OA_Data_Snapshots__c d = OA_TestDataUtility.createDataSnapShots();
        d.OA_Probability__c = 50;
        d.OA_Region__c = 'Europe';
        OA_Data_Snapshots__c d1 = OA_TestDataUtility.createDataSnapShots();
        d1.OA_Probability__c = 80;
        d1.OA_Region__c = 'APAC & MEA';
        OA_Data_Snapshots__c d2 = OA_TestDataUtility.createDataSnapShots();
        d2.OA_Probability__c = 100;
        d2.OA_Region__c = 'East NA';
        dataSnapList.add(d);
        dataSnapList.add(d1);
        dataSnapList.add(d2);
        insert dataSnapList;
        Test.startTest();
        	OA_BR_WeightedGrossPipelineCntrl cont = new OA_BR_WeightedGrossPipelineCntrl();
        	cont.apacProbability='70';
            cont.eastCoatsProbability='60';
            cont.europeProbability='70';
            cont.westCoatsProbability='50';
            cont.selectedMonth = String.valueOf(Date.today().month());
            cont.selectedYear = String.valueOf(date.today().year());
     
        	cont.prepareReportData();
        Test.stopTest();
    }
}