force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <formula>January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_BR_BookedSalesVSHAvrgsCntrl.cls
public class OA_BR_BookedSalesVSHAvrgsCntrl {
    public String selectedYear{get;set;}
    public String selectedMonth{get;set;}    
    public List<SelectOption> months{get;set;}
    public List<SelectOption> years{get;set;}
    public List<ReportData> dataList{get;set;}
    public Map<String, String> monthMap{get;set;}
    
    public OA_BR_BookedSalesVSHAvrgsCntrl(){
        init();
    }
    
    
    
    public void init(){
        months = OA_ReportUtility.getMonthList();
        years = OA_ReportUtility.getYearList();       
        selectedYear   =  String.valueOf(System.today().year());
        selectedMonth  =  String.valueOf(System.today().month()-1);
        prepareReportData();
    }
    
    public void prepareReportData(){  
        
        dataList = new List<ReportData>();
        try{        
            if(Integer.valueOf(selectedYear) == System.today().year() &&
               (Integer.valueOf(selectedMonth) > System.today().month() )
              ){
                  OA_Utility.addMessage('Snapshot month must not be greater than the current month for year: '+selectedYear, 'Info');
                  return;
              }
            Integer averageStartYear = Integer.valueOf(selectedYear) - Integer.valueOf(Label.OA_ReportAverageYears) < = 2016 
                					   ? 2016 : Integer.valueOf(selectedYear) - Integer.valueOf(Label.OA_ReportAverageYears);
            If(averageStartYear == Integer.valueOf(selectedYear)){
                OA_Utility.addMessage('Historical Data not found for selected year', 'Info');
                return;
            }
            
            Map<String, Decimal> pYearsTotalSold = new Map<String, Decimal>();
            Integer count = 0;
            for(integer i=averageStartYear; i<Integer.valueOf(selectedYear); i++){
                Map<String, Decimal> pYearSold = getYearEndSoldByRegion(String.valueOf(i), selectedMonth);  
                if(pYearSold == null) return;
                for(String region : pYearSold.keyset()){
                    if(!pYearsTotalSold.containsKey(region))pYearsTotalSold.put(region,0);
                    pYearsTotalSold.put(region, pYearsTotalSold.get(region)+pYearSold.get(region));
                }
                count += 1;
            }
            Map<String, Decimal> selectedYearSold = getYearEndSoldByRegion(selectedYear, selectedMonth);
            if(selectedYearSold == null){
                OA_Utility.addMessage('Snapshot not captured for selected year and month', 'Info');
                return;
            } 
            for(String region : pYearsTotalSold.keyset()){
                ReportData data = new ReportData();
                data.Region = region;
                data.pAvrg = (pYearsTotalSold.get(region)/(count*1000)).setScale(2);
                data.bookedSales = selectedYearSold != null && selectedYearSold.containsKey(region) && selectedYearSold.get(region) != null ? (selectedYearSold.get(region)/1000).setScale(2): 0;
                if(data.pAvrg == null || data.bookedSales == 0) continue;
                data.difference = (data.bookedSales - data.pAvrg);
                dataList.add(data);           
            }   
        }Catch(Exception e){
            OA_Utility.addMessage('Something went wrong, contact your system admin.', 'Error');
        }     
    }
    
    public Map<String, Decimal> getYearEndSoldByRegion(String year, String month){
        List<AggregateResult> results = new List<AggregateResult>(
            [Select OA_Region__c,Sum(Gross__c) FROM OA_Data_Snapshots__c 
            WHERE OA_Year__c =:year AND Snapshot_Month__c =:month AND OA_Probability__c = 100  
            Group By Rollup(OA_Region__c)]
        );
        if(results.isEmpty()) return null;
        Map<String, Decimal>  monthlySoldMap = new Map<String, Decimal>();
        for(AggregateResult result : results){
            String key = (String)result.get('OA_Region__c');            
            if(key == null || key == '') key = 'Global';
            monthlySoldMap.put(key, (Decimal)result.get('expr0'));
        }
        return monthlySoldMap;
    }
    
    
    
    public class ReportData{
        public String Region{get;set;}
        public Decimal pAvrg{get;set;}
        public Decimal bookedSales{get;set;}
        public Decimal difference{get;set;}
    }

}