force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <label>August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <label>December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <label>November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Account__c.field-meta.xml
<CustomField>
    <fullName>OA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Snapshots</relationshipLabel>
    <relationshipName>Data_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Data Snapshots</relationshipLabel>
    <relationshipName>Data_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_User__c.field-meta.xml
<CustomField>
    <fullName>OA_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Data_Snapshots_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <label>October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Opportunity_Rep__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Data_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>OA_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Forecast</relationshipLabel>
    <relationshipName>OA_Revenue_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <formula>OA_Opportunity__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Risk_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>OA_Risk_Adjusted__c</fullName>
    <formula>OA_Sales_Revenue__c *  OA_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Risk Adjusted</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Sales_Revenue__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Forecasted monthly revenue</description>
    <label>Sales Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Total_Sales_Revenue_Incl_CRs__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Sales_Revenue_Incl_CRs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total Sales Revenue including the changes via various CRs</inlineHelpText>
    <label>Total Sales Revenue (Incl CRs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery Milestone</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/OA_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Owner_Region__c</fullName>
    <formula>TEXT(Owner.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OA_Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>OA_Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Change Request</relationshipLabel>
    <relationshipName>ChangeRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <businessProcess>Project</businessProcess>
    <description>Default Record Type, to capture all Opportunities (Prospective Projects)</description>
    <label>Project</label>
</RecordType>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_SnapshotsBatch.cls
/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_SnapshotsBatch
Class Purpose: Batch class to create data snapshots records on Monthly Basis
Versions: 1.1
******************************************************************************************************/
global class OA_SnapshotsBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    Integer totalCount = 0;
    Integer successCount = 0;
    Integer failedCount = 0;
    List<String> failedIds = new List<String>();
    
    global Database.QueryLocator start(Database.BatchableContext bc){
       
        String currentYearVal = String.valueOf(Date.today().year());
        delete [Select Id from OA_Data_Snapshots__c 
                WHERE Snapshot_Month__c =: String.valueOf(date.today().month()) 
                AND OA_Year__c =: currentYearVal
                LIMIT 9999                    
               ];
        String query = 'SELECT id, name, AccountId, Account.Name, Probability, OA_Parent_Project__c, RecordType.developerName, OA_Parent_Project__r.Account.Name, OwnerId, OA_Owner_Region__c, (Select id, convertCurrency(OA_Sales_Revenue__c), OA_Month__c, convertCurrency(OA_Risk_Adjusted__c), convertCurrency(OA_Total_Sales_Revenue_Incl_CRs__c) FROM OA_Revenue_Forecasts__r WHERE RecordType.DeveloperName = \'Delivery\' AND OA_Year__c = \'' + currentYearVal + '\') FROM Opportunity WHERE Probability <> 0 AND RecordType.developerName = \'Project\' AND Id IN (Select OA_Opportunity__c FROM OA_Revenue_Forecast__c WHERE RecordType.DeveloperName = \'Delivery\' AND OA_Year__c = \'' + currentYearVal + '\')';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope){
        System.debug('******** Execute Method Executing **************');

        List<OA_Data_Snapshots__c> snapList = new List<OA_Data_Snapshots__c>();		
        totalCount += scope.size();
        for(Opportunity opp : scope){
            if(opp.OA_Revenue_Forecasts__r.size() > 0){
                OA_Data_Snapshots__c ds = new OA_Data_Snapshots__c();
                ds.Opportunity_Name__c = opp.Name;
                ds.OA_Opportunity__c = opp.Id;
                ds.OA_Region__c = opp.OA_Owner_Region__c;
                ds.Snapshot_Month__c = String.valueOf(date.today().month());
                ds.Snapshot_Date__c = Date.today();                 
                ds.Opportunity_Rep__c = opp.OwnerId;
                ds.Account_Name__c = opp.Account.Name;
                ds.OA_Account__c = opp.AccountId;
                ds.OA_Probability__c = opp.Probability;
                ds.Name = String.valueOf(Date.today().Month()) + '-' + String.valueOf(Date.today().Year()) + String.valueOf(opp.Id);
                ds.OA_User__c = opp.OwnerId;
                ds.OA_Year__c = String.valueOf(Date.today().Year());
                for(OA_Revenue_Forecast__c rev : opp.OA_Revenue_Forecasts__r){
                    if(rev.OA_Month__c == '1'){
                        ds.January__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '2'){
                        ds.February__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '3'){
                        ds.March__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '4'){
                        ds.April__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '5'){
                        ds.May__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '6'){
                        ds.June__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '7'){
                        ds.July__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '8'){
                        ds.August__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '9'){
                        ds.September__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '10'){
                        ds.October__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '11'){
                        ds.November__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                    else if(rev.OA_Month__c == '12'){
                        ds.December__c = opp.Probability == 100 ? rev.OA_Total_Sales_Revenue_Incl_CRs__c : rev.OA_Total_Sales_Revenue_Incl_CRs__c/1000;
                    }
                }
                snapList.add(ds);
        	}
        }
        System.debug('Records Processed : '+snapList.size());
        
        if(!snapList.isEmpty()){        
            List<Database.SaveResult> results = Database.insert(snapList, false);
            integer index = 0;
            for(Database.SaveResult result : results){
                if(!result.isSuccess()){
                    failedCount += 1;
                    String errorMsg = '';
                    for(Database.Error err: result.getErrors()){
                        errorMsg += err.getMessage();
                    }
                    failedIds.add(snapList.get(index).Name+' - '+errorMsg);
                }else{
                    successCount += 1;
                }
                index += 1;
            }            
        }
        
    }  
    
    global void finish(Database.BatchableContext bc){
        System.debug('******** Finish Method Executing **************');
    	sendMail(UserInfo.getUserEmail(), null);
        System.debug('******** Mail Sended **************');
    }
    
    global void execute(SchedulableContext sc){
        OA_SnapshotsBatch runBatch = new OA_SnapshotsBatch();
        Database.executeBatch(runBatch,50);
    }
    
    public void sendMail(String toMail, String ccMail){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        string[] to = new string[] {toMail};
        string[] cc = new string[] {ccMail};         
        email.setToAddresses(to);
        String body = 'Total Record : '+totalCount + '\n';
        body += 'Success Record : '+successCount+ '\n';
        body += 'Failed Record : '+failedCount+ '\n';
        if(failedIds.size() > 0){
             body += JSON.serializePretty(failedIds);
        }
        if(ccMail!=null && ccMail != '')
            email.setCcAddresses(cc);
                 
        email.setSubject('Snapshot Batch Processed');         
        email.setPlainTextBody(body);
        try{
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        }catch(exception e){
            System.debug('Error:'+e.getMessage()+'\n'+e.getStackTraceString());
        }
         

    }
}