force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <formula>January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_BR_TopTenAccountCntrl.cls
public class OA_BR_TopTenAccountCntrl {
    public string selectedRegion{get;set;}
    public string selectedMonth{get;set;}   
    public string selectedYear{get;set;}    
    public List<SelectOption> regions{get;set;}
    public List<SelectOption> months{get;set;}
    public List<SelectOption> years{get;set;}
    
    public List<ReportData> reportDataList{get;set;}
    
    public OA_BR_TopTenAccountCntrl(){
        init();
    }
    
    public void init(){
        regions = OA_ReportUtility.getRegionList();
        years = OA_ReportUtility.getYearList();
        months = OA_ReportUtility.getMonthList();
        selectedRegion = 'Global';       
        selectedMonth  = String.valueOf(System.today().month()-1);
        selectedYear   = String.valueOf(System.today().year());  
        prepareReportData();
    }
    
    public void prepareReportData(){
        reportDataList = new List<ReportData>();
        List<AggregateResult> topTenAccounts = new List<AggregateResult>();
        List<AggregateResult> others = new List<AggregateResult>();
        try{
            if(Integer.valueOf(selectedYear) == System.today().year() &&
               (Integer.valueOf(selectedMonth) > System.today().month() ))
            {
                OA_Utility.addMessage('Snapshot month must not be greater than the current month for year: '+selectedYear, 'Info');
                return;
            }
            List<AggregateResult> aggregateResults = new List<AggregateResult>(
                [Select Account_Name__c, OA_Region__c, SUM(Gross__c) 
                 FROM OA_Data_Snapshots__c 
                 WHERE OA_Year__c=: selectedYear AND Snapshot_Month__c =:selectedMonth AND OA_Probability__c = 100 
                 Group By Account_Name__c,OA_Region__c
                  HAVING  SUM(Gross__c)>=50000
                 ORDER BY SUM(Gross__c) DESC
                ]
            );
            
            if(aggregateResults.isEmpty()){
                OA_Utility.addMessage('Snapshot not captured for selected month and year.', 'Info');
                return;
            }
            Decimal totalSold = 0.0;
            for(AggregateResult ar : aggregateResults){
                if(selectedRegion != 'Global' && selectedRegion != (String)ar.get('OA_Region__c') ) continue;
                topTenAccounts.add(ar);                               
                totalSold += (Double)ar.get('expr0');            
            }    
            
            for(AggregateResult ar : topTenAccounts){
                ReportData data = new ReportData(
                    (String)ar.get('Account_Name__c'),
                    (Double)ar.get('expr0'),
                    ((Double)ar.get('expr0')/totalSold)*100
                );  
                
                reportDataList.add(data);
            }
            
            /*Decimal otherAccountSold = 0.0;
            for(AggregateResult ar : others){
                otherAccountSold += (Double)ar.get('expr0');
            } 
            reportDataList.add(new ReportData('',null,null));           
            reportDataList.add(new ReportData('Others',otherAccountSold,(otherAccountSold/totalSold)* 100));*/
            reportDataList.add(new ReportData('',null,null));   
            reportDataList.add(new ReportData('Total',totalSold,100));   
            
            
        }Catch(Exception e){
            System.debug('Error:'+e.getMessage());
            System.debug('StackTrac:'+e.getStackTraceString());
            OA_Utility.addMessage('Data not found for selected criteria. Change the criteria and try again.', 'Info');
        }
        
    }
    
    public class ReportData{
        public String AccountName{get;set;}
        public Decimal Sold{get;set;}
        public Decimal SoldPercentage{get;set;}
        
        public ReportData(String AccountName, Decimal Sold, Decimal SoldPercentage){
            this.AccountName = AccountName;
            this.Sold = Sold != null ? (Sold/1000).setscale(2) : null;
            this.SoldPercentage = SoldPercentage!=null ? SoldPercentage.setScale(2) : null;
        }
    }
    
}