force-app/main/default/objects/OA_Monthly_Quota__c/OA_Monthly_Quota__c.object-meta.xml
<CustomObject>
    <label>Monthly Quota</label>
    <nameField>
        <displayFormat>MQ-{00000000}</displayFormat>
        <label>Monthly Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Quotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Forecast__c.field-meta.xml
<CustomField>
    <fullName>OA_Forecast__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Is_Forecast_Editable__c.field-meta.xml
<CustomField>
    <fullName>OA_Is_Forecast_Editable__c</fullName>
    <formula>IF( 
OR(TEXT(OA_Month__c) = TEXT(MONTH(Today())), (TEXT(OA_Month__c) = TEXT(MONTH(Today()) + 1 )), (TEXT(OA_Month__c) = TEXT(MONTH(Today()) + 2))), TRUE, FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Forecast Editable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Stretch_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Stretch_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Stretch Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East Coast US</fullName>
            </value>
            <value>
                <fullName>West Coast US</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Target__c</fullName>
    <label>Sales Quota</label>
    <referenceTo>Sales_Quota__c</referenceTo>
    <relationshipLabel>Monthly Quotas</relationshipLabel>
    <relationshipName>Monthly_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <formula>TEXT(OA_Sales_Target__r.OA_Year__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/Sales_Quota__c.object-meta.xml
<CustomObject>
    <label>Sales Quota</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Sales Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Account__c.field-meta.xml
<CustomField>
    <fullName>OA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Quotas</relationshipLabel>
    <relationshipName>Sales_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Annual_Sales_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Annual_Sales_Quota__c</fullName>
    <label>Annual Sales Quota(Target))</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Monthly_Quota__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Annual_Stretch_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Annual_Stretch_Quota__c</fullName>
    <label>Annual Stretch Quota</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Monthly_Stretch_Quota__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_CSO__c.field-meta.xml
<CustomField>
    <fullName>OA_CSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
                <isActive>false</isActive>
                <label>Global</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Gross_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Gross_Pipeline__c</fullName>
    <label>Total Gross Pipeline</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Gross_Pipeline__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Risk_Adjusted_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Risk_Adjusted_Pipeline__c</fullName>
    <label>Total Risk Adjusted Pipeline</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Risk_Adjusted_Pipeline__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Sold_Revenue__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Sold_Revenue__c</fullName>
    <inlineHelpText>New Sales Closed This Year</inlineHelpText>
    <label>Total Sold Revenue</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Sold_Revenue__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/recordTypes/Agent_Target.recordType-meta.xml
<RecordType>
    <fullName>Agent_Target</fullName>
    <active>true</active>
    <label>CSO Target</label>
</RecordType>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
                <label>North America West</label>
            </value>
            <value>
                <fullName>East NA</fullName>
                <label>North America East</label>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
                <default>true</default>
                <label>APAC &amp; MEA</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OA_AccountSalesQuotaController.cls
public class OA_AccountSalesQuotaController {
    
    public String yearSelected{get;set;}
    public string salesQuotaId {get;set;}
    public Double agentSalesQuota{get;set;}
    public Double totalSoldRev{get;set;}
    public Double totalWeightedPipeline{get;set;}
    public Double totalunWeightedPipeline{get;set;}
    public String CSOSelected{get;set;}
    public Map<Integer,OA_Monthly_Quota__c> displayMap{get;set;}
    public String csoName{get;set;}
    public String accName{get;set;}
    public Boolean errOnPage{get;set;}
    public List<Integer> iList{get;set;}
    public Map<Integer,Boolean> renderMap{get;set;}
	public OA_AccountSalesQuotaController(ApexPages.StandardController controller){
        try{
    	Sales_Quota__c temp = (Sales_Quota__c)controller.getRecord();
        salesQuotaId = temp.id;
        Sales_Quota__C sqRec = [SELECT id, OA_Account__r.Name, OA_Account__r.OwnerId, OA_CSO__r.Name, OA_CSO__r.Region__c, OA_Region__c, OA_Year__c, OA_Annual_Sales_Quota__c, OA_Annual_Stretch_Quota__c FROM Sales_Quota__c WHERE Id =: temp.id];
        errOnPage = False;
        CSOSelected = UserInfo.getUserId();
        //validateUser(sqRec);
        yearSelected = sqRec.OA_Year__c;
        csoName = sqRec.OA_CSO__r.Name;
        accName = sqRec.OA_Account__r.Name;
        Sales_Quota__c sqAgentRec = [SELECT id, OA_Annual_Sales_Quota__c, OA_Total_Sold_Revenue__c, OA_Total_Risk_Adjusted_Pipeline__c, OA_Total_Gross_Pipeline__c FROM Sales_Quota__c WHERE RecordType.DeveloperName = 'Agent_Target' AND OA_CSO__c =: CSOSelected AND OA_Year__c =: yearSelected ];
        agentSalesQuota = sqAgentRec.OA_Annual_Sales_Quota__c;
        totalSoldRev = sqAgentRec.OA_Total_Sold_Revenue__c;
		totalWeightedPipeline = sqAgentRec.OA_Total_Risk_Adjusted_Pipeline__c;  
        totalunWeightedPipeline = sqAgentRec.OA_Total_Gross_Pipeline__c;
        displayMap = new Map<Integer,OA_Monthly_Quota__c>();
        forecastRecordsToBeDisplayed();
        initializeRows();
        }
        Catch(Exception e){
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Account Owners Target is not Set'));     
  
        }
    }    
    public void forecastRecordsToBeDisplayed(){
        iList = new List<Integer>();
        if(String.valueOf(Date.today().year()) == yearSelected){
        	iList.add(Date.today().month());
        }    
        if(String.valueOf((Date.today().addMonths(1)).year()) == yearSelected){
        	iList.add((Date.today().addMonths(1)).month());
        }
        if(String.valueOf((Date.today().addMonths(2)).year()) == yearSelected){
        	iList.add((Date.today().addMonths(2)).month());
        }    
    }
    public PageReference validateUser(Sales_Quota__c sq){
        if(sq.OA_Account__r.OwnerId <> CSOSelected){
            errOnPage = TRUE;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You are not authorized to view this record.')); 
        }
        return null;
    }
    public void initializeRows(){
        Map<Integer,String> monthMap = new Map<Integer,String> {1 => 'January', 2 => 'February', 3 => 'March', 4 => 'April', 5 => 'May', 6 => 'June', 7 => 'July', 8 => 'August', 9 => 'September', 10 => 'October', 11 => 'November', 12 => 'December'};
        List<OA_Monthly_Quota__c> existingMQList = [SELECT id, OA_Month__c, OA_Monthly_Quota__c, OA_Is_Forecast_Editable__c , OA_Forecast__c, OA_Monthly_Stretch_Quota__c FROM OA_Monthly_Quota__c WHERE OA_Sales_Target__c =: salesQuotaId];
        if(!existingMQList.isEmpty()){
            for(OA_Monthly_Quota__c m : existingMQList){
                //AgentWrapper aw = new AgentWrapper(m,Integer.valueOf(m.OA_Month__c));
                //wrapList.add(aw);
                displayMap.put(Integer.valueOf(m.OA_Month__c),m);
            }
        }
        for(Integer i =1; i< 13;i++){
            OA_Monthly_Quota__c m = new OA_Monthly_Quota__c(OA_Month__c = String.valueOf(i),OA_Sales_Target__c = salesQuotaId);
            //AgentWrapper aw = new AgentWrapper(m,i);
            //wrapList.add(aw);
            if(!displayMap.containsKey(i)){
            	displayMap.put(i,m);    
            }
        }
        
        
        renderMap = new Map<Integer,Boolean>();
        if(displayMap <> null){
        //List<Integer> keyList = new List<Integer>();
        //keyList.addAll(displayMap.keySet());    
            for(Integer i : displayMap.keySet()){
                if(iList.contains(i)){
                    renderMap.put(i,TRUE);
                }
                else{
                    renderMap.put(i,FALSE);
                }
                
                //if(i == Date.today().month() || (i == Date.today().month()))
                //AgentWrapper aw = new AgentWrapper(displayMap.get(i),i);
            	//wrapList.add(aw);
            }
            System.debug('yup'+renderMap);
        }
    }
    
    public PageReference save(){
        List<OA_Monthly_Quota__c> recToUpsert = new List<OA_Monthly_Quota__c>();
        try{
            for(Integer i : displayMap.keySet()){
                if(displayMap.get(i).id == null && displayMap.get(i).OA_Monthly_Quota__c == 0 && displayMap.get(i).OA_Monthly_Stretch_Quota__c == 0 && (displayMap.get(i).OA_Forecast__c == 0 || displayMap.get(i).OA_Forecast__c == null)){
                    continue;
                }    
                else{
                    recToUpsert.add(displayMap.get(i));
                }
            }      
            upsert recToUpsert;
            PageReference pr = new PageReference('/'+salesQuotaId);
            pr.setRedirect(true);
            return pr;
        }
        catch(Exception ex){
            if(ex.getMessage().contains('cannot edit forecast on monthly quota')){
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'You cannot edit forecast on monthly quota outside three months from today.'));     
            }            
        }
        return null;
    }
    
    public PageReference cancel(){
        PageReference pr = new PageReference('/'+salesQuotaId);
   		pr.setRedirect(true);
        return pr;
    }
    public Class AgentWrapper{
        public OA_Monthly_Quota__c mq{get;set;}
        public Boolean editForecast{get;set;}
        public AgentWrapper(OA_Monthly_Quota__c moQ, Boolean b){
            this.mq =  moQ;
            this.editForecast = b;
        }
    }
}