force-app/main/default/objects/OA_Monthly_Quota__c/OA_Monthly_Quota__c.object-meta.xml
<CustomObject>
    <label>Monthly Quota</label>
    <nameField>
        <displayFormat>MQ-{00000000}</displayFormat>
        <label>Monthly Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Quotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Stretch_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Stretch_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Stretch Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East Coast US</fullName>
            </value>
            <value>
                <fullName>West Coast US</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Target__c</fullName>
    <label>Sales Quota</label>
    <referenceTo>Sales_Quota__c</referenceTo>
    <relationshipLabel>Monthly Quotas</relationshipLabel>
    <relationshipName>Monthly_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <formula>TEXT(OA_Sales_Target__r.OA_Year__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/Sales_Quota__c.object-meta.xml
<CustomObject>
    <label>Sales Quota</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Sales Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Annual_Sales_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Annual_Sales_Quota__c</fullName>
    <label>Annual Sales Quota(Target))</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Monthly_Quota__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Annual_Stretch_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Annual_Stretch_Quota__c</fullName>
    <label>Annual Stretch Quota</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Monthly_Stretch_Quota__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_CSO__c.field-meta.xml
<CustomField>
    <fullName>OA_CSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
                <isActive>false</isActive>
                <label>Global</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Gross_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Gross_Pipeline__c</fullName>
    <label>Total Gross Pipeline</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Gross_Pipeline__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Risk_Adjusted_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Risk_Adjusted_Pipeline__c</fullName>
    <label>Total Risk Adjusted Pipeline</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Risk_Adjusted_Pipeline__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Total_Sold_Revenue__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Sold_Revenue__c</fullName>
    <inlineHelpText>New Sales Closed This Year</inlineHelpText>
    <label>Total Sold Revenue</label>
    <summarizedField>OA_Monthly_Quota__c.OA_Sold_Revenue__c</summarizedField>
    <summaryForeignKey>OA_Monthly_Quota__c.OA_Sales_Target__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/recordTypes/Regional_Target.recordType-meta.xml
<RecordType>
    <fullName>Regional_Target</fullName>
    <active>true</active>
    <label>Regional Target</label>
</RecordType>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
                <label>North America West</label>
            </value>
            <value>
                <fullName>East NA</fullName>
                <label>North America East</label>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
                <default>true</default>
                <label>APAC &amp; MEA</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OA_AgentSalesQuotaController.cls
public class OA_AgentSalesQuotaController {
	
    public String yearSelected{get;set;}
    public string salesQuotaId {get;set;}
    public String region{get;set;}
    public Double regionalSalesQuota{get;set;}
    public Double totalSoldRev{get;set;}
    public Double totalWeightedPipeline{get;set;}
    public Double totalunWeightedPipeline{get;set;}
    public List<OA_Monthly_Quota__c> mqList{get;set;}
    public List<OA_Monthly_Quota__c> recToDeleteList{get;set;}
    public String removeRowId{get;set;}
    public String removeRowNum{get;set;}
    public String CSOSelected{get;set;}
    public List<AgentWrapper> wrapList{get;set;}
    public Map<Integer,OA_Monthly_Quota__c> displayMap{get;set;}
    
    public OA_AgentSalesQuotaController(ApexPages.StandardController controller){
        try{
    	Sales_Quota__c temp = (Sales_Quota__c)controller.getRecord();
        salesQuotaId = temp.id;
        Sales_Quota__C sqRec = [SELECT id, OA_CSO__r.Name, OA_CSO__r.Region__c, OA_Region__c, OA_Year__c, OA_Annual_Sales_Quota__c, OA_Annual_Stretch_Quota__c FROM Sales_Quota__c WHERE Id =: temp.id];
        yearSelected = sqRec.OA_Year__c;
        CSOSelected = sqRec.OA_CSO__r.Name;
        region = sqRec.OA_CSO__r.Region__c;
        Sales_Quota__c sqRegionRec = [SELECT id, OA_Annual_Sales_Quota__c, OA_Total_Sold_Revenue__c, OA_Total_Risk_Adjusted_Pipeline__c, OA_Total_Gross_Pipeline__c FROM Sales_Quota__c WHERE RecordType.DeveloperName = 'Regional_Target' AND  OA_Region__c =: region AND OA_Year__c =: yearSelected ];
        regionalSalesQuota = sqRegionRec.OA_Annual_Sales_Quota__c;
        totalSoldRev = sqRegionRec.OA_Total_Sold_Revenue__c;
		totalWeightedPipeline = sqRegionRec.OA_Total_Risk_Adjusted_Pipeline__c;  
        totalunWeightedPipeline = sqRegionRec.OA_Total_Gross_Pipeline__c;  
        wrapList = new List<AgentWrapper>();
        displayMap = new Map<Integer,OA_Monthly_Quota__c>();
            initializeRows();}
        Catch(Exception e){
            System.debug(e);
        }
    }
    
    public void initializeRows(){
        Map<Integer,String> monthMap = new Map<Integer,String> {1 => 'January', 2 => 'February', 3 => 'March', 4 => 'April', 5 => 'May', 6 => 'June', 7 => 'July', 8 => 'August', 9 => 'September', 10 => 'October', 11 => 'November', 12 => 'December'};
        List<OA_Monthly_Quota__c> existingMQList = [SELECT id, OA_Month__c, OA_Monthly_Quota__c, OA_Monthly_Stretch_Quota__c FROM OA_Monthly_Quota__c WHERE OA_Sales_Target__c =: salesQuotaId];
        if(!existingMQList.isEmpty()){
            for(OA_Monthly_Quota__c m : existingMQList){
                AgentWrapper aw = new AgentWrapper(m,Integer.valueOf(m.OA_Month__c));
                //wrapList.add(aw);
                displayMap.put(Integer.valueOf(m.OA_Month__c),m);
            }
        }
        for(Integer i =1; i< 13;i++){
            OA_Monthly_Quota__c m = new OA_Monthly_Quota__c(OA_Month__c = String.valueOf(i),OA_Sales_Target__c = salesQuotaId);
            AgentWrapper aw = new AgentWrapper(m,i);
            //wrapList.add(aw);
            if(!displayMap.containsKey(i)){
            	displayMap.put(i,m);    
            }
        }
        
        if(displayMap <> null){
        List<Integer> keyList = new List<Integer>();
        keyList.addAll(displayMap.keySet());    
            for(Integer i : keyList){
                AgentWrapper aw = new AgentWrapper(displayMap.get(i),i);
            	wrapList.add(aw);
            }
        }
    }
    
    public PageReference save(){
        List<OA_Monthly_Quota__c> recToUpsert = new List<OA_Monthly_Quota__c>();
        for(Integer i : displayMap.keySet()){
            if(displayMap.get(i).id == null && displayMap.get(i).OA_Monthly_Quota__c == 0 && displayMap.get(i).OA_Monthly_Stretch_Quota__c == 0){
            	continue;
            }    
            else{
                recToUpsert.add(displayMap.get(i));
            }
        }      
        upsert recToUpsert;
        PageReference pr = new PageReference('/'+salesQuotaId);
   		pr.setRedirect(true);
        return pr;
    }
    
    public PageReference cancel(){
        PageReference pr = new PageReference('/'+salesQuotaId);
   		pr.setRedirect(true);
        return pr;
    }
    
    public Class AgentWrapper{
        public OA_Monthly_Quota__c mq{get;set;}
        public Integer index{get;set;}
        public AgentWrapper(OA_Monthly_Quota__c moQ, Integer i){
            this.mq =  moQ;
            this.index = i;
        }
    }
}