force-app/main/default/objects/OA_Monthly_Quota__c/OA_Monthly_Quota__c.object-meta.xml
<CustomObject>
    <label>Monthly Quota</label>
    <nameField>
        <displayFormat>MQ-{00000000}</displayFormat>
        <label>Monthly Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Quotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Revenue_Forecast__c/OA_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Custom field to capture revenue forecast. OLI cannot be used as the  user can submit forecast for multiple years and the same needs to be reported sepratly</description>
    <label>Revenue Forecast</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Revenue Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Quota__c/Sales_Quota__c.object-meta.xml
<CustomObject>
    <label>Sales Quota</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Sales Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OA_TestSalesQuotaCalculation.cls
@isTest
public class OA_TestSalesQuotaCalculation {
    
    @isTest
    public static void testSOLDCalculation(){
        Account acc = OA_TestDataUtility.createAccount();
        insert acc;
        
        Opportunity opp = OA_TestDataUtility.createOpportunity(acc);
        insert opp;
        
        List<OA_Revenue_Forecast__c> rfList = OA_TestDataUtility.createRevForecast(opp);
        insert rfList;
        
        Sales_Quota__c sq = OA_TestDataUtility.createCSOSalesQuota();
        insert sq;
        Sales_Quota__c accsq = OA_TestDataUtility.createAccountSalesQuota(acc);
        insert accsq;
        Sales_Quota__c regsq = OA_TestDataUtility.createRegionalSalesQuota();
        insert regsq;
        
        OA_Monthly_Quota__c mq1 = OA_TestDataUtility.createMonthlyQuota(sq);
        insert mq1;
        
        OA_Monthly_Quota__c mq2= OA_TestDataUtility.createMonthlyQuota(accsq);
        insert mq2;
        
        OA_Monthly_Quota__c mq3 = OA_TestDataUtility.createMonthlyQuota(regsq);
        insert mq3;
        
        OA_SalesQuotaCalculation cal = new OA_SalesQuotaCalculation();
        Database.executeBatch(cal);
    }
    
    @isTest
    public static void testPipelineCalculation(){
        Account acc = OA_TestDataUtility.createAccount();
        insert acc;
        
        Opportunity opp = OA_TestDataUtility.createOpportunity(acc);
        opp.StageName = 'Proposed';
        insert opp;
        
        List<OA_Revenue_Forecast__c> rfList = OA_TestDataUtility.createRevForecast(opp);
        insert rfList;
        
        Sales_Quota__c sq = OA_TestDataUtility.createCSOSalesQuota();
        insert sq;
        Sales_Quota__c accsq = OA_TestDataUtility.createAccountSalesQuota(acc);
        insert accsq;
        Sales_Quota__c regsq = OA_TestDataUtility.createRegionalSalesQuota();
        insert regsq;
        
        OA_Monthly_Quota__c mq1 = OA_TestDataUtility.createMonthlyQuota(sq);
        insert mq1;
        
        OA_Monthly_Quota__c mq2= OA_TestDataUtility.createMonthlyQuota(accsq);
        insert mq2;
        
        OA_Monthly_Quota__c mq3 = OA_TestDataUtility.createMonthlyQuota(regsq);
        insert mq3;
        
        OA_SalesQuotaCalculation cal = new OA_SalesQuotaCalculation();
        Database.executeBatch(cal);
    }
    
    
    
}