force-app/main/default/objects/OA_Budget__c/OA_Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Budget__c/OA_Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Monthly Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/OA_Budget__c.field-meta.xml
<CustomField>
    <fullName>OA_Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>OA_Budget__c</referenceTo>
    <relationshipLabel>Monthly Distribution</relationshipLabel>
    <relationshipName>Monthly_Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OA_BR_YTDCummulativeRevCntrl_Test.cls
@isTest
public class OA_BR_YTDCummulativeRevCntrl_Test {
    public static testMethod void testReportData(){
        Account a = OA_TestDataUtility.createAccount();
        insert a;
         OA_Budget__c sq = OA_TestDataUtility.createBudget();
        insert sq;
         OA_Monthly_Budget__c mq= OA_TestDataUtility.createMonthlyBudget(sq);
    insert mq;
        List<List<OA_Data_Snapshots__c>> dataSnapList = new List<List<OA_Data_Snapshots__c>>();
        List<OA_Data_Snapshots__c> d = OA_TestDataUtility.createMultipleDataSnapShots(2016);
        
        List<OA_Data_Snapshots__c> d1 = OA_TestDataUtility.createMultipleDataSnapShots(2017);
         
        List<OA_Data_Snapshots__c> d2 = OA_TestDataUtility.createMultipleDataSnapShots(2018);
        
        insert d;
        insert d1;
        insert d2;
        Test.startTest();
        	OA_BR_YTDCummulativeRevCntrl cont = new OA_BR_YTDCummulativeRevCntrl();
        	cont.selectedMonth = String.valueOf(Date.today().month());
        	cont.selectedRegion = 'Europe';
        	cont.selectedYear = String.valueOf(date.today().year());
        	cont.prepareReportData();
        
        OA_BR_YTDCummulativeRevCntrl contt = new OA_BR_YTDCummulativeRevCntrl();
        	contt.selectedMonth = String.valueOf(Date.today().month());
        	contt.selectedRegion = 'Global';
        	contt.selectedYear = String.valueOf(date.today().year()-3);
        	contt.prepareReportData();
        Test.stopTest();
    }
}