force-app/main/default/objects/OA_Budget__c/OA_Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Budget__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Budget__c/fields/OA_Total_Budget__c.field-meta.xml
<CustomField>
    <fullName>OA_Total_Budget__c</fullName>
    <label>Total Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Budget__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <label>August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <label>December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <formula>January__c + February__c+ March__c + April__c+May__c+June__c+July__c+August__c+September__c+October__c+November__c+December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <label>November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <label>October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/Snapshot_Month__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Month__c</fullName>
    <label>Snapshot Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/OA_Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Monthly Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <label>February</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <label>January</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <label>March</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/OA_Budget__c.field-meta.xml
<CustomField>
    <fullName>OA_Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>OA_Budget__c</referenceTo>
    <relationshipLabel>Monthly Distribution</relationshipLabel>
    <relationshipName>Monthly_Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <label>September</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/OA_Monthly_Quota__c.object-meta.xml
<CustomObject>
    <label>Monthly Quota</label>
    <nameField>
        <displayFormat>MQ-{00000000}</displayFormat>
        <label>Monthly Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Quotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Month__c.field-meta.xml
<CustomField>
    <fullName>OA_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Monthly_Quota__c.field-meta.xml
<CustomField>
    <fullName>OA_Monthly_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East Coast US</fullName>
            </value>
            <value>
                <fullName>West Coast US</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Sales_Target__c.field-meta.xml
<CustomField>
    <fullName>OA_Sales_Target__c</fullName>
    <label>Sales Quota</label>
    <referenceTo>Sales_Quota__c</referenceTo>
    <relationshipLabel>Monthly Quotas</relationshipLabel>
    <relationshipName>Monthly_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OA_Monthly_Quota__c/fields/OA_Year__c.field-meta.xml
<CustomField>
    <fullName>OA_Year__c</fullName>
    <formula>TEXT(OA_Sales_Target__r.OA_Year__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/Sales_Quota__c.object-meta.xml
<CustomObject>
    <label>Sales Quota</label>
    <nameField>
        <displayFormat>SQ-{0000000}</displayFormat>
        <label>Sales Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Quota__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>Unidentified</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
                <isActive>false</isActive>
                <label>Global</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Quota__c/recordTypes/Regional_Target.recordType-meta.xml
<RecordType>
    <fullName>Regional_Target</fullName>
    <active>true</active>
    <label>Regional Target</label>
</RecordType>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OA_ReportUtility.cls
public class OA_ReportUtility {
    public static Decimal getYearEndRevenue(String year, String region, String month){
        String baseQuery = 'SELECT SUM(Gross__c) FROM OA_Data_Snapshots__c';
        String whereClouse =' WHERE OA_Probability__c = 100 AND OA_Year__c =\''+year+'\' AND Snapshot_Month__c = \''+month+'\'';
        if(region != null && region != 'Global'){
            whereClouse += ' AND OA_Region__c=\''+region+'\'';
        }
        String query = baseQuery + whereClouse;
        System.debug('query:'+query);
        List<AggregateResult> results = new List<AggregateResult>(
            (List<AggregateResult>)Database.query(query)
        );
        if(results == null || results.isEmpty()) return 0;
        return (Decimal)results[0].get('expr0');      
    }
    
    public static Decimal getYearEndRevenue(String year, String region){
        String baseQuery = 'SELECT SUM(Gross__c) FROM OA_Data_Snapshots__c';
        String whereClouse =' WHERE OA_Probability__c = 100 AND OA_Year__c =\''+year+'\' AND Snapshot_Month__c = \'12\'';
        if(region != null && region != 'Global'){
            whereClouse += ' AND OA_Region__c=\''+region+'\'';
        }
        String query = baseQuery + whereClouse;
        System.debug('query:'+query);
        List<AggregateResult> results = new List<AggregateResult>(
            (List<AggregateResult>)Database.query(query)
        );
        if(results == null || results.isEmpty()) return 0;
        return (Decimal)results[0].get('expr0');      
    }
    
    public static Decimal getYearEndBudget(String year, String region){
        String baseQuery = 'SELECT SUM(OA_Total_Budget__c) FROM OA_Budget__c';
        String whereClouse =' WHERE OA_Year__c =\''+year+'\'';
        if(region != null && region != 'Global'){
            whereClouse += ' AND OA_Region__c=\''+region+'\'';
        }
        String query = baseQuery + whereClouse;
        List<AggregateResult> results = new List<AggregateResult>(
            (List<AggregateResult>)Database.query(query)
        );
        if(results == null || results.isEmpty()) return 0;
        return (Decimal)results[0].get('expr0');   
 
    }
    
    public static List<SelectOption> getRegionList() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Global','Global'));
        options.add(new SelectOption('Europe','Europe'));
        options.add(new SelectOption('East NA','East NA'));
        options.add(new SelectOption('West NA','West NA'));
        options.add(new SelectOption('APAC & MEA','APAC & MEA'));
        return options;
    }
    
    public static List<SelectOption> getYearList(){
        Integer currentYear = System.today().year();
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption(String.valueOf(currentYear),String.valueOf(currentYear)));
        options.add(new SelectOption(String.valueOf(currentYear-1),String.valueOf(currentYear-1)));
        options.add(new SelectOption(String.valueOf(currentYear-2),String.valueOf(currentYear-2)));
        options.add(new SelectOption(String.valueOf(currentYear-3),String.valueOf(currentYear-3)));
        return options;
    }
    
    public static Map<String, String> getMonthMap(){
        Map<String, String> monthMap = new Map<String, String>();
        monthMap.put('12','December');
        monthMap.put('11','November');
        monthMap.put('10','October');
        monthMap.put('9','September');
        monthMap.put('8','August');
        monthMap.put('7','July');
        monthMap.put('6','June');
        monthMap.put('5','May');
        monthMap.put('4','April');
        monthMap.put('3','March');
        monthMap.put('2','February');
        monthMap.put('1','January');
        return monthMap;       
    }
    
    public static List<SelectOption> getMonthList(){
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('1','January'));
        options.add(new SelectOption('2','February'));
        options.add(new SelectOption('3','March'));
        options.add(new SelectOption('4','April'));
        options.add(new SelectOption('5','May'));
        options.add(new SelectOption('6','June'));
        options.add(new SelectOption('7','July'));
        options.add(new SelectOption('8','August'));
        options.add(new SelectOption('9','September'));
        options.add(new SelectOption('10','October'));
        options.add(new SelectOption('11','November'));
        options.add(new SelectOption('12','December'));
        return options;
    }
    
    public static Map<String, Map<String, Decimal>> getRegionlQuotaByMonth(String year){
        if(year == null || year == '') return null;
        Map<String, Map<String, Decimal>> regionalMonthlyBudget = new Map<String, Map<String, Decimal>>();
        Map<String,String> monthMap = getMonthMap();
        List<AggregateResult> budgetResults = new List<AggregateResult>(
            [select OA_Budget__r.OA_Region__c region, SUM(January__c), SUM(February__c), SUM(March__c), SUM(April__c),SUM(May__c),SUM(June__c),SUM(July__c),SUM(August__c),SUM(September__c),SUM(October__c),SUM(November__c),SUM(December__c) FROM OA_Monthly_Budget__c 
             WHERE OA_Budget__r.OA_Year__c =:year 
             Group By Rollup(OA_Budget__r.OA_Region__c)
            ]
        );
        for(AggregateResult result : budgetResults){
            String region = (String)result.get('region');
            if(!regionalMonthlyBudget.containsKey(region)) regionalMonthlyBudget.put(region, new Map<String, Decimal>());
            for(Integer i=0; i<12; i++){
                String expr = 'expr'+String.valueOf(i);
                regionalMonthlyBudget.get(region).put(monthMap.get(String.valueOf(i+1)), (Decimal)result.get(expr));
            }
        }
        
        /*for(OA_Monthly_Quota__c mq : [SELECT OA_Sales_Target__r.OA_Region__c, OA_Month__c, OA_Monthly_Quota__c FROM OA_Monthly_Quota__c WHERE OA_Sales_Target__r.RecordType.DeveloperName = 'Regional_Target' AND OA_Year__c=: year]){
            if(!regionalMonthlyBudget.containsKey(mq.OA_Sales_Target__r.OA_Region__c)){
                regionalMonthlyBudget.put(mq.OA_Sales_Target__r.OA_Region__c, new Map<String, Decimal>());
            }
            regionalMonthlyBudget.get(mq.OA_Sales_Target__r.OA_Region__c).put(monthMap.get(mq.OA_Month__c), mq.OA_Monthly_Quota__c);
        }*/
        return regionalMonthlyBudget;
    }
    
}