force-app/main/default/objects/OA_Budget__c/OA_Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Budget__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/OA_Data_Snapshots__c.object-meta.xml
<CustomObject>
    <description>This object is created to capture Monthly Data snapshot of Opportunity. This is only for Reporting requirement and is not used anywhere else</description>
    <label>Data Snapshots</label>
    <nameField>
        <label>Data Snapshots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Probability__c.field-meta.xml
<CustomField>
    <fullName>OA_Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OA_Data_Snapshots__c/fields/OA_Region__c.field-meta.xml
<CustomField>
    <fullName>OA_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West NA</fullName>
            </value>
            <value>
                <fullName>East NA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>APAC &amp; MEA</fullName>
            </value>
            <value>
                <fullName>East Cost (US)</fullName>
                <isActive>false</isActive>
                <label>East Cost (US)</label>
            </value>
            <value>
                <fullName>West Cost (US)</fullName>
                <isActive>false</isActive>
                <label>West Cost (US)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OA_Monthly_Budget__c/OA_Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Monthly Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budget</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OA_Monthly_Budget__c/fields/OA_Budget__c.field-meta.xml
<CustomField>
    <fullName>OA_Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>OA_Budget__c</referenceTo>
    <relationshipLabel>Monthly Distribution</relationshipLabel>
    <relationshipName>Monthly_Budget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OA_BR_SalesGoalViewCntrl_Test.cls
@isTest
public class OA_BR_SalesGoalViewCntrl_Test {
    public static testMethod void validateReport(){
        Account a = OA_TestDataUtility.createAccount();
        insert a;
          OA_Budget__c sq = OA_TestDataUtility.createBudget();
        insert sq;
         OA_Monthly_Budget__c mq= OA_TestDataUtility.createMonthlyBudget(sq);
    insert mq;
        List<OA_Data_Snapshots__c> dataSnapList = new List<OA_Data_Snapshots__c>();
        OA_Data_Snapshots__c d = OA_TestDataUtility.createDataSnapShots();
        
        OA_Data_Snapshots__c d1 = OA_TestDataUtility.createDataSnapShots();
        d1.OA_Probability__c = 100;
        
        OA_Data_Snapshots__c d2 = OA_TestDataUtility.createDataSnapShots();
        
        d2.OA_Region__c = '';
        
        
        dataSnapList.add(d);
        dataSnapList.add(d1);
        dataSnapList.add(d2);
        
        insert dataSnapList;
        Test.startTest();
        OA_BR_SalesGoalViewCntrl cont = new OA_BR_SalesGoalViewCntrl();
            cont.selectedMonth = String.valueOf(Date.today().month());        
            cont.selectedYear = String.valueOf(date.today().year());
            cont.search();
        OA_BR_SalesGoalViewCntrl contt = new OA_BR_SalesGoalViewCntrl();
            contt.selectedMonth = String.valueOf(Date.today().month());        
            contt.selectedYear = String.valueOf(date.today().year()-1);
            contt.search();
        Test.stopTest();
    }
}